package operation

import op "github.com/lwmacct/251117-go-ddd-template/pkg/operation"

// ============================================================================
// 操作注册表
// ============================================================================

// operationRegistry 操作注册表（单一数据源）
//
// URN-Centric RBAC:
//   - Operation code 本身即权限标识符（URN 格式）
//   - scope 为 "public" 的操作无需权限检查
//   - 非公开操作默认需要权限检查
//
//nolint:gochecknoglobals // 注册表是只读全局配置
var operationRegistry = op.Registry[operationMeta]{
	// ==================== Public 域（公开） ====================
	PublicAuthRegister: {
		Method:         POST,
		Path:           "/api/auth/register",
		Tags:           "Authentication",
		AuditAction:    "auth.register",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpCreate,
		Summary:        "注册",
		Description:    "用户注册",
	},
	PublicAuthLogin: {
		Method:         POST,
		Path:           "/api/auth/login",
		Tags:           "Authentication",
		AuditAction:    "auth.login",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpAuthenticate,
		Summary:        "登录",
		Description:    "用户登录",
	},
	PublicAuthLogin2FA: {
		Method:         POST,
		Path:           "/api/auth/login/2fa",
		Tags:           "Authentication",
		AuditAction:    "auth.login_2fa",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpAuthenticate,
		Summary:        "2FA 登录",
		Description:    "两步验证登录",
	},
	PublicAuthRefresh: {
		Method:         POST,
		Path:           "/api/auth/refresh",
		Tags:           "Authentication",
		AuditAction:    "auth.refresh",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpAuthenticate,
		Summary:        "刷新令牌",
		Description:    "刷新访问令牌",
	},
	PublicAuthCaptcha: {
		Method:      GET,
		Path:        "/api/auth/captcha",
		Tags:        "Authentication",
		Summary:     "获取验证码",
		Description: "获取图形验证码",
	},

	// ==================== Self 域 - 2FA（需认证） ====================
	Self2FASetup: {
		Method:         POST,
		Path:           "/api/auth/2fa/setup",
		Tags:           "Authentication - 2FA",
		AuditAction:    "auth.2fa_setup",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpUpdate,
		Summary:        "设置 2FA",
		Description:    "设置两步验证",
	},
	Self2FAVerify: {
		Method:         POST,
		Path:           "/api/auth/2fa/verify",
		Tags:           "Authentication - 2FA",
		AuditAction:    "auth.2fa_enable",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpUpdate,
		Summary:        "启用 2FA",
		Description:    "验证并启用两步验证",
	},
	Self2FADisable: {
		Method:         POST,
		Path:           "/api/auth/2fa/disable",
		Tags:           "Authentication - 2FA",
		AuditAction:    "auth.2fa_disable",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpUpdate,
		Summary:        "禁用 2FA",
		Description:    "禁用两步验证",
	},
	Self2FAStatus: {
		Method:      GET,
		Path:        "/api/auth/2fa/status",
		Tags:        "Authentication - 2FA",
		Summary:     "2FA 状态",
		Description: "获取两步验证状态",
	},

	// ==================== Sys 域 - 用户管理 ====================
	SysUsersCreate: {
		Method:         POST,
		Path:           "/api/system/users",
		Tags:           "Admin - User Management",
		AuditAction:    "user.create",
		AuditCategory:  AuditCatUser,
		AuditOperation: AuditOpCreate,
		Summary:        "创建用户",
		Description:    "创建新用户",
	},
	SysUsersBatchCreate: {
		Method:         POST,
		Path:           "/api/system/users/batch",
		Tags:           "Admin - User Management",
		AuditAction:    "user.batch_create",
		AuditCategory:  AuditCatUser,
		AuditOperation: AuditOpCreate,
		Summary:        "批量创建用户",
		Description:    "批量创建用户",
	},
	SysUsersList: {
		Method:      GET,
		Path:        "/api/system/users",
		Tags:        "Admin - User Management",
		Summary:     "用户列表",
		Description: "获取用户列表",
	},
	SysUsersGet: {
		Method:      GET,
		Path:        "/api/system/users/:id",
		Tags:        "Admin - User Management",
		Summary:     "用户详情",
		Description: "获取用户详情",
	},
	SysUsersUpdate: {
		Method:         PUT,
		Path:           "/api/system/users/:id",
		Tags:           "Admin - User Management",
		AuditAction:    "user.update",
		AuditCategory:  AuditCatUser,
		AuditOperation: AuditOpUpdate,
		Summary:        "更新用户",
		Description:    "更新用户信息",
	},
	SysUsersDelete: {
		Method:         DELETE,
		Path:           "/api/system/users/:id",
		Tags:           "Admin - User Management",
		AuditAction:    "user.delete",
		AuditCategory:  AuditCatUser,
		AuditOperation: AuditOpDelete,
		Summary:        "删除用户",
		Description:    "删除用户",
	},
	SysUsersAssignRoles: {
		Method:         PUT,
		Path:           "/api/system/users/:id/roles",
		Tags:           "Admin - User Management",
		AuditAction:    "user.assign_roles",
		AuditCategory:  AuditCatUser,
		AuditOperation: AuditOpUpdate,
		Summary:        "分配角色",
		Description:    "为用户分配角色",
	},

	// ==================== Sys 域 - 角色管理 ====================
	SysRolesCreate: {
		Method:         POST,
		Path:           "/api/system/roles",
		Tags:           "Admin - Role Management",
		AuditAction:    "role.create",
		AuditCategory:  AuditCatRole,
		AuditOperation: AuditOpCreate,
		Summary:        "创建角色",
		Description:    "创建角色",
	},
	SysRolesList: {
		Method:      GET,
		Path:        "/api/system/roles",
		Tags:        "Admin - Role Management",
		Summary:     "角色列表",
		Description: "获取角色列表",
	},
	SysRolesGet: {
		Method:      GET,
		Path:        "/api/system/roles/:id",
		Tags:        "Admin - Role Management",
		Summary:     "角色详情",
		Description: "获取角色详情",
	},
	SysRolesUpdate: {
		Method:         PUT,
		Path:           "/api/system/roles/:id",
		Tags:           "Admin - Role Management",
		AuditAction:    "role.update",
		AuditCategory:  AuditCatRole,
		AuditOperation: AuditOpUpdate,
		Summary:        "更新角色",
		Description:    "更新角色",
	},
	SysRolesDelete: {
		Method:         DELETE,
		Path:           "/api/system/roles/:id",
		Tags:           "Admin - Role Management",
		AuditAction:    "role.delete",
		AuditCategory:  AuditCatRole,
		AuditOperation: AuditOpDelete,
		Summary:        "删除角色",
		Description:    "删除角色",
	},
	SysRolesSetPermissions: {
		Method:         PUT,
		Path:           "/api/system/roles/:id/permissions",
		Tags:           "Admin - Role Management",
		AuditAction:    "role.set_permissions",
		AuditCategory:  AuditCatRole,
		AuditOperation: AuditOpUpdate,
		Summary:        "设置权限",
		Description:    "设置角色权限",
	},

	// ==================== Sys 域 - 操作列表 ====================
	SysOperationsList: {
		Method:      GET,
		Path:        "/api/system/operations",
		Tags:        "System",
		Summary:     "操作列表",
		Description: "获取可用操作列表",
	},

	// ==================== Sys 域 - 审计日志 ====================
	SysAuditLogsList: {
		Method:      GET,
		Path:        "/api/system/auditlogs",
		Tags:        "Admin - Audit Log",
		Summary:     "审计日志列表",
		Description: "获取审计日志列表",
	},
	SysAuditLogsGet: {
		Method:      GET,
		Path:        "/api/system/auditlogs/:id",
		Tags:        "Admin - Audit Log",
		Summary:     "审计日志详情",
		Description: "获取审计日志详情",
	},
	SysAuditLogsActions: {
		Method:      GET,
		Path:        "/api/system/auditlogs/actions",
		Tags:        "Admin - Audit Log",
		Summary:     "审计操作定义",
		Description: "获取审计操作定义",
	},

	// ==================== Sys 域 - 菜单管理 ====================
	SysMenusCreate: {
		Method:         POST,
		Path:           "/api/system/menus",
		Tags:           "Admin - Menu Management",
		AuditAction:    "menu.create",
		AuditCategory:  AuditCatMenu,
		AuditOperation: AuditOpCreate,
		Summary:        "创建菜单",
		Description:    "创建菜单",
	},
	SysMenusList: {
		Method:      GET,
		Path:        "/api/system/menus",
		Tags:        "Admin - Menu Management",
		Summary:     "菜单列表",
		Description: "获取菜单列表",
	},
	SysMenusGet: {
		Method:      GET,
		Path:        "/api/system/menus/:id",
		Tags:        "Admin - Menu Management",
		Summary:     "菜单详情",
		Description: "获取菜单详情",
	},
	SysMenusUpdate: {
		Method:         PUT,
		Path:           "/api/system/menus/:id",
		Tags:           "Admin - Menu Management",
		AuditAction:    "menu.update",
		AuditCategory:  AuditCatMenu,
		AuditOperation: AuditOpUpdate,
		Summary:        "更新菜单",
		Description:    "更新菜单",
	},
	SysMenusDelete: {
		Method:         DELETE,
		Path:           "/api/system/menus/:id",
		Tags:           "Admin - Menu Management",
		AuditAction:    "menu.delete",
		AuditCategory:  AuditCatMenu,
		AuditOperation: AuditOpDelete,
		Summary:        "删除菜单",
		Description:    "删除菜单",
	},
	SysMenusReorder: {
		Method:         POST,
		Path:           "/api/system/menus/reorder",
		Tags:           "Admin - Menu Management",
		AuditAction:    "menu.reorder",
		AuditCategory:  AuditCatMenu,
		AuditOperation: AuditOpUpdate,
		Summary:        "重排菜单",
		Description:    "重排菜单顺序",
	},

	// ==================== Sys 域 - 系统概览 ====================
	SysOverviewStats: {
		Method:      GET,
		Path:        "/api/system/overview/stats",
		Tags:        "Overview",
		Summary:     "系统概览",
		Description: "获取系统概览统计",
	},

	// ==================== Sys 域 - 系统配置 ====================
	SysSettingsCreate: {
		Method:         POST,
		Path:           "/api/system/settings",
		Tags:           "Admin - Settings",
		AuditAction:    "setting.create",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpCreate,
		Summary:        "创建配置",
		Description:    "创建配置项",
	},
	SysSettingsList: {
		Method:      GET,
		Path:        "/api/system/settings",
		Tags:        "Admin - Settings",
		Summary:     "配置列表",
		Description: "获取配置列表",
	},
	SysSettingsGet: {
		Method:      GET,
		Path:        "/api/system/settings/:key",
		Tags:        "Admin - Settings",
		Summary:     "配置详情",
		Description: "获取配置详情",
	},
	SysSettingsUpdate: {
		Method:         PUT,
		Path:           "/api/system/settings/:key",
		Tags:           "Admin - Settings",
		AuditAction:    "setting.update",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpUpdate,
		Summary:        "更新配置",
		Description:    "更新配置",
	},
	SysSettingsDelete: {
		Method:         DELETE,
		Path:           "/api/system/settings/:key",
		Tags:           "Admin - Settings",
		AuditAction:    "setting.delete",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpDelete,
		Summary:        "删除配置",
		Description:    "删除配置",
	},
	SysSettingsBatchUpdate: {
		Method:         POST,
		Path:           "/api/system/settings/batch",
		Tags:           "Admin - Settings",
		AuditAction:    "setting.batch_update",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpUpdate,
		Summary:        "批量更新配置",
		Description:    "批量更新配置",
	},

	// ==================== Sys 域 - 配置分类 ====================
	SysSettingCategoriesList: {
		Method:      GET,
		Path:        "/api/system/settings/categories",
		Tags:        "Admin - Setting Categories",
		Summary:     "配置分类列表",
		Description: "获取配置分类列表",
	},
	SysSettingCategoriesGet: {
		Method:      GET,
		Path:        "/api/system/settings/categories/:id",
		Tags:        "Admin - Setting Categories",
		Summary:     "配置分类详情",
		Description: "获取配置分类详情",
	},
	SysSettingCategoriesCreate: {
		Method:         POST,
		Path:           "/api/system/settings/categories",
		Tags:           "Admin - Setting Categories",
		AuditAction:    "setting_category.create",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpCreate,
		Summary:        "创建配置分类",
		Description:    "创建配置分类",
	},
	SysSettingCategoriesUpdate: {
		Method:         PUT,
		Path:           "/api/system/settings/categories/:id",
		Tags:           "Admin - Setting Categories",
		AuditAction:    "setting_category.update",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpUpdate,
		Summary:        "更新配置分类",
		Description:    "更新配置分类",
	},
	SysSettingCategoriesDelete: {
		Method:         DELETE,
		Path:           "/api/system/settings/categories/:id",
		Tags:           "Admin - Setting Categories",
		AuditAction:    "setting_category.delete",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpDelete,
		Summary:        "删除配置分类",
		Description:    "删除配置分类",
	},

	// ==================== Sys 域 - 缓存管理 ====================
	SysCacheInfo: {
		Method:      GET,
		Path:        "/api/system/cache/info",
		Tags:        "System",
		Summary:     "缓存信息",
		Description: "获取缓存信息",
	},
	SysCacheScanKeys: {
		Method:      GET,
		Path:        "/api/system/cache/keys",
		Tags:        "System",
		Summary:     "扫描缓存键",
		Description: "扫描缓存键",
	},
	SysCacheGetKey: {
		Method:      GET,
		Path:        "/api/system/cache/key",
		Tags:        "System",
		Summary:     "获取缓存值",
		Description: "获取缓存键值",
	},
	SysCacheDeleteKey: {
		Method:         DELETE,
		Path:           "/api/system/cache/key",
		Tags:           "System",
		AuditAction:    "cache.delete",
		AuditCategory:  AuditCatCache,
		AuditOperation: AuditOpDelete,
		Summary:        "删除缓存键",
		Description:    "删除缓存键",
	},
	SysCacheDeletePattern: {
		Method:         DELETE,
		Path:           "/api/system/cache/keys",
		Tags:           "System",
		AuditAction:    "cache.delete_pattern",
		AuditCategory:  AuditCatCache,
		AuditOperation: AuditOpDelete,
		Summary:        "批量删除缓存",
		Description:    "按模式删除缓存键",
	},

	// ==================== Self 域 - 个人资料 ====================
	SelfProfileGet: {
		Method:      GET,
		Path:        "/api/user/profile",
		Tags:        "User - Profile",
		Summary:     "获取资料",
		Description: "获取当前用户资料",
	},
	SelfProfileUpdate: {
		Method:         PUT,
		Path:           "/api/user/profile",
		Tags:           "User - Profile",
		AuditAction:    "profile.update",
		AuditCategory:  AuditCatProfile,
		AuditOperation: AuditOpUpdate,
		Summary:        "更新资料",
		Description:    "更新当前用户资料",
	},
	SelfPasswordUpdate: {
		Method:         PUT,
		Path:           "/api/user/password",
		Tags:           "User - Profile",
		AuditAction:    "password.update",
		AuditCategory:  AuditCatProfile,
		AuditOperation: AuditOpUpdate,
		Summary:        "修改密码",
		Description:    "修改密码",
	},
	SelfAccountDelete: {
		Method:         DELETE,
		Path:           "/api/user/account",
		Tags:           "User - Profile",
		AuditAction:    "account.delete",
		AuditCategory:  AuditCatProfile,
		AuditOperation: AuditOpDelete,
		Summary:        "注销账户",
		Description:    "删除账户",
	},

	// ==================== Self 域 - 访问令牌 ====================
	SelfTokensCreate: {
		Method:         POST,
		Path:           "/api/user/tokens",
		Tags:           "User - Personal Access Token",
		AuditAction:    "token.create",
		AuditCategory:  AuditCatToken,
		AuditOperation: AuditOpCreate,
		Summary:        "创建令牌",
		Description:    "创建访问令牌",
	},
	SelfTokensList: {
		Method:      GET,
		Path:        "/api/user/tokens",
		Tags:        "User - Personal Access Token",
		Summary:     "令牌列表",
		Description: "获取访问令牌列表",
	},
	SelfTokensGet: {
		Method:      GET,
		Path:        "/api/user/tokens/:id",
		Tags:        "User - Personal Access Token",
		Summary:     "令牌详情",
		Description: "获取令牌详情",
	},
	SelfTokensDelete: {
		Method:         DELETE,
		Path:           "/api/user/tokens/:id",
		Tags:           "User - Personal Access Token",
		AuditAction:    "token.delete",
		AuditCategory:  AuditCatToken,
		AuditOperation: AuditOpDelete,
		Summary:        "删除令牌",
		Description:    "删除令牌",
	},
	SelfTokensDisable: {
		Method:         PATCH,
		Path:           "/api/user/tokens/:id/disable",
		Tags:           "User - Personal Access Token",
		AuditAction:    "token.disable",
		AuditCategory:  AuditCatToken,
		AuditOperation: AuditOpUpdate,
		Summary:        "禁用令牌",
		Description:    "禁用令牌",
	},
	SelfTokensEnable: {
		Method:         PATCH,
		Path:           "/api/user/tokens/:id/enable",
		Tags:           "User - Personal Access Token",
		AuditAction:    "token.enable",
		AuditCategory:  AuditCatToken,
		AuditOperation: AuditOpUpdate,
		Summary:        "启用令牌",
		Description:    "启用令牌",
	},

	// ==================== Self 域 - 用户配置 ====================
	SelfSettingsCategoriesList: {
		Method:      GET,
		Path:        "/api/user/settings/categories",
		Tags:        "User - Settings",
		Summary:     "配置分类列表",
		Description: "获取用户配置分类",
	},
	SelfSettingsList: {
		Method:      GET,
		Path:        "/api/user/settings",
		Tags:        "User - Settings",
		Summary:     "用户配置列表",
		Description: "获取所有用户配置",
	},
	SelfSettingsGet: {
		Method:      GET,
		Path:        "/api/user/settings/:key",
		Tags:        "User - Settings",
		Summary:     "用户配置详情",
		Description: "获取用户配置项",
	},
	SelfSettingsSet: {
		Method:         PUT,
		Path:           "/api/user/settings/:key",
		Tags:           "User - Settings",
		AuditAction:    "user_setting.set",
		AuditCategory:  AuditCatUserSetting,
		AuditOperation: AuditOpUpdate,
		Summary:        "设置用户配置",
		Description:    "设置用户配置",
	},
	SelfSettingsReset: {
		Method:         DELETE,
		Path:           "/api/user/settings/:key",
		Tags:           "User - Settings",
		AuditAction:    "user_setting.reset",
		AuditCategory:  AuditCatUserSetting,
		AuditOperation: AuditOpUpdate,
		Summary:        "重置用户配置",
		Description:    "重置用户配置",
	},
	SelfSettingsBatchSet: {
		Method:         POST,
		Path:           "/api/user/settings/batch",
		Tags:           "User - Settings",
		AuditAction:    "user_setting.batch_set",
		AuditCategory:  AuditCatUserSetting,
		AuditOperation: AuditOpUpdate,
		Summary:        "批量设置配置",
		Description:    "批量设置用户配置",
	},
}
