package operation

import op "github.com/lwmacct/251117-go-ddd-template/pkg/operation"

// operationRegistry 操作注册表（单一数据源）
//
// URN-Centric RBAC:
//   - Operation code 本身即权限标识符（URN 格式）
//   - scope 为 "public" 的操作无需权限检查
//   - 非公开操作默认需要权限检查
//
//nolint:gochecknoglobals // 注册表是只读全局配置
var operationRegistry = op.Registry[operationMeta]{
	// ==================== Public 域（公开） ====================
	PublicAuthRegister: {
		Method:         HttpPOST,
		Path:           "/api/auth/register",
		AuditAction:    "auth.register",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpCreate,
		Label:          "注册",
		Description:    "User registration",
		Group:          "认证 (Auth)",
	},
	PublicAuthLogin: {
		Method:         HttpPOST,
		Path:           "/api/auth/login",
		AuditAction:    "auth.login",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpAuthenticate,
		Label:          "登录",
		Description:    "User login",
		Group:          "认证 (Auth)",
	},
	PublicAuthLogin2FA: {
		Method:         HttpPOST,
		Path:           "/api/auth/login/2fa",
		AuditAction:    "auth.login_2fa",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpAuthenticate,
		Label:          "2FA 登录",
		Description:    "Two-factor authentication login",
		Group:          "认证 (Auth)",
	},
	PublicAuthRefresh: {
		Method:         HttpPOST,
		Path:           "/api/auth/refresh",
		AuditAction:    "auth.refresh",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpAuthenticate,
		Label:          "刷新令牌",
		Description:    "Refresh access token",
		Group:          "认证 (Auth)",
	},
	PublicAuthCaptcha: {
		Method:      HttpGET,
		Path:        "/api/auth/captcha",
		Label:       "获取验证码",
		Description: "Get captcha image",
		Group:       "认证 (Auth)",
	},

	// ==================== Self 域 - 2FA（需认证） ====================
	Self2FASetup: {
		Method:         HttpPOST,
		Path:           "/api/auth/2fa/setup",
		AuditAction:    "auth.2fa_setup",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpUpdate,
		Label:          "设置 2FA",
		Description:    "Setup two-factor authentication",
		Group:          "认证 - 2FA (Auth - 2FA)",
	},
	Self2FAVerify: {
		Method:         HttpPOST,
		Path:           "/api/auth/2fa/verify",
		AuditAction:    "auth.2fa_enable",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpUpdate,
		Label:          "启用 2FA",
		Description:    "Verify and enable 2FA",
		Group:          "认证 - 2FA (Auth - 2FA)",
	},
	Self2FADisable: {
		Method:         HttpPOST,
		Path:           "/api/auth/2fa/disable",
		AuditAction:    "auth.2fa_disable",
		AuditCategory:  AuditCatAuth,
		AuditOperation: AuditOpUpdate,
		Label:          "禁用 2FA",
		Description:    "Disable two-factor authentication",
		Group:          "认证 - 2FA (Auth - 2FA)",
	},
	Self2FAStatus: {
		Method:      HttpGET,
		Path:        "/api/auth/2fa/status",
		Label:       "2FA 状态",
		Description: "Get 2FA status",
		Group:       "认证 - 2FA (Auth - 2FA)",
	},

	// ==================== Sys 域 - 用户管理 ====================
	SysUsersCreate: {
		Method:         HttpPOST,
		Path:           "/api/system/users",
		AuditAction:    "user.create",
		AuditCategory:  AuditCatUser,
		AuditOperation: AuditOpCreate,
		Label:          "创建用户",
		Description:    "Create new user",
		Group:          "系统管理 - 用户管理 (Sys - User)",
	},
	SysUsersBatchCreate: {
		Method:         HttpPOST,
		Path:           "/api/system/users/batch",
		AuditAction:    "user.batch_create",
		AuditCategory:  AuditCatUser,
		AuditOperation: AuditOpCreate,
		Label:          "批量创建用户",
		Description:    "Batch create users",
		Group:          "系统管理 - 用户管理 (Sys - User)",
	},
	SysUsersList: {
		Method:      HttpGET,
		Path:        "/api/system/users",
		Label:       "用户列表",
		Description: "List users",
		Group:       "系统管理 - 用户管理 (Sys - User)",
	},
	SysUsersGet: {
		Method:      HttpGET,
		Path:        "/api/system/users/:id",
		Label:       "用户详情",
		Description: "Get user by ID",
		Group:       "系统管理 - 用户管理 (Sys - User)",
	},
	SysUsersUpdate: {
		Method:         HttpPUT,
		Path:           "/api/system/users/:id",
		AuditAction:    "user.update",
		AuditCategory:  AuditCatUser,
		AuditOperation: AuditOpUpdate,
		Label:          "更新用户",
		Description:    "Update user",
		Group:          "系统管理 - 用户管理 (Sys - User)",
	},
	SysUsersDelete: {
		Method:         HttpDELETE,
		Path:           "/api/system/users/:id",
		AuditAction:    "user.delete",
		AuditCategory:  AuditCatUser,
		AuditOperation: AuditOpDelete,
		Label:          "删除用户",
		Description:    "Delete user",
		Group:          "系统管理 - 用户管理 (Sys - User)",
	},
	SysUsersAssignRoles: {
		Method:         HttpPUT,
		Path:           "/api/system/users/:id/roles",
		AuditAction:    "user.assign_roles",
		AuditCategory:  AuditCatUser,
		AuditOperation: AuditOpUpdate,
		Label:          "分配角色",
		Description:    "Assign roles to user",
		Group:          "系统管理 - 用户管理 (Sys - User)",
	},

	// ==================== Sys 域 - 角色管理 ====================
	SysRolesCreate: {
		Method:         HttpPOST,
		Path:           "/api/system/roles",
		AuditAction:    "role.create",
		AuditCategory:  AuditCatRole,
		AuditOperation: AuditOpCreate,
		Label:          "创建角色",
		Description:    "Create role",
		Group:          "系统管理 - 角色管理 (Sys - Role)",
	},
	SysRolesList: {
		Method:      HttpGET,
		Path:        "/api/system/roles",
		Label:       "角色列表",
		Description: "List roles",
		Group:       "系统管理 - 角色管理 (Sys - Role)",
	},
	SysRolesGet: {
		Method:      HttpGET,
		Path:        "/api/system/roles/:id",
		Label:       "角色详情",
		Description: "Get role by ID",
		Group:       "系统管理 - 角色管理 (Sys - Role)",
	},
	SysRolesUpdate: {
		Method:         HttpPUT,
		Path:           "/api/system/roles/:id",
		AuditAction:    "role.update",
		AuditCategory:  AuditCatRole,
		AuditOperation: AuditOpUpdate,
		Label:          "更新角色",
		Description:    "Update role",
		Group:          "系统管理 - 角色管理 (Sys - Role)",
	},
	SysRolesDelete: {
		Method:         HttpDELETE,
		Path:           "/api/system/roles/:id",
		AuditAction:    "role.delete",
		AuditCategory:  AuditCatRole,
		AuditOperation: AuditOpDelete,
		Label:          "删除角色",
		Description:    "Delete role",
		Group:          "系统管理 - 角色管理 (Sys - Role)",
	},
	SysRolesSetPermissions: {
		Method:         HttpPUT,
		Path:           "/api/system/roles/:id/permissions",
		AuditAction:    "role.set_permissions",
		AuditCategory:  AuditCatRole,
		AuditOperation: AuditOpUpdate,
		Label:          "设置权限",
		Description:    "Set role permissions",
		Group:          "系统管理 - 角色管理 (Sys - Role)",
	},

	// ==================== Sys 域 - 操作列表 ====================
	SysOperationsList: {
		Method:      HttpGET,
		Path:        "/api/system/operations",
		Label:       "操作列表",
		Description: "List available operations",
		Group:       "系统管理 - 操作管理 (Sys - Operation)",
	},

	// ==================== Sys 域 - 审计日志 ====================
	SysAuditLogsList: {
		Method:      HttpGET,
		Path:        "/api/system/auditlogs",
		Label:       "审计日志列表",
		Description: "List audit logs",
		Group:       "系统管理 - 审计日志 (Sys - Audit Log)",
	},
	SysAuditLogsGet: {
		Method:      HttpGET,
		Path:        "/api/system/auditlogs/:id",
		Label:       "审计日志详情",
		Description: "Get audit log by ID",
		Group:       "系统管理 - 审计日志 (Sys - Audit Log)",
	},
	SysAuditLogsActions: {
		Method:      HttpGET,
		Path:        "/api/system/auditlogs/actions",
		Label:       "审计操作定义",
		Description: "Get audit action definitions",
		Group:       "系统管理 - 审计日志 (Sys - Audit Log)",
	},

	// ==================== Sys 域 - 菜单管理 ====================
	SysMenusCreate: {
		Method:         HttpPOST,
		Path:           "/api/system/menus",
		AuditAction:    "menu.create",
		AuditCategory:  AuditCatMenu,
		AuditOperation: AuditOpCreate,
		Label:          "创建菜单",
		Description:    "Create menu",
		Group:          "系统管理 - 菜单管理 (Sys - Menu)",
	},
	SysMenusList: {
		Method:      HttpGET,
		Path:        "/api/system/menus",
		Label:       "菜单列表",
		Description: "List menus",
		Group:       "系统管理 - 菜单管理 (Sys - Menu)",
	},
	SysMenusGet: {
		Method:      HttpGET,
		Path:        "/api/system/menus/:id",
		Label:       "菜单详情",
		Description: "Get menu by ID",
		Group:       "系统管理 - 菜单管理 (Sys - Menu)",
	},
	SysMenusUpdate: {
		Method:         HttpPUT,
		Path:           "/api/system/menus/:id",
		AuditAction:    "menu.update",
		AuditCategory:  AuditCatMenu,
		AuditOperation: AuditOpUpdate,
		Label:          "更新菜单",
		Description:    "Update menu",
		Group:          "系统管理 - 菜单管理 (Sys - Menu)",
	},
	SysMenusDelete: {
		Method:         HttpDELETE,
		Path:           "/api/system/menus/:id",
		AuditAction:    "menu.delete",
		AuditCategory:  AuditCatMenu,
		AuditOperation: AuditOpDelete,
		Label:          "删除菜单",
		Description:    "Delete menu",
		Group:          "系统管理 - 菜单管理 (Sys - Menu)",
	},
	SysMenusReorder: {
		Method:         HttpPOST,
		Path:           "/api/system/menus/reorder",
		AuditAction:    "menu.reorder",
		AuditCategory:  AuditCatMenu,
		AuditOperation: AuditOpUpdate,
		Label:          "重排菜单",
		Description:    "Reorder menus",
		Group:          "系统管理 - 菜单管理 (Sys - Menu)",
	},

	// ==================== Sys 域 - 系统概览 ====================
	SysOverviewStats: {
		Method:      HttpGET,
		Path:        "/api/system/overview/stats",
		Label:       "系统概览",
		Description: "Get system overview stats",
		Group:       "系统管理 - 系统概览 (Sys - Overview)",
	},

	// ==================== Sys 域 - 系统配置 ====================
	SysSettingsCreate: {
		Method:         HttpPOST,
		Path:           "/api/system/settings",
		AuditAction:    "setting.create",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpCreate,
		Label:          "创建配置",
		Description:    "Create setting",
		Group:          "系统管理 - 系统配置 (Sys - Setting)",
	},
	SysSettingsList: {
		Method:      HttpGET,
		Path:        "/api/system/settings",
		Label:       "配置列表",
		Description: "List settings",
		Group:       "系统管理 - 系统配置 (Sys - Setting)",
	},
	SysSettingsGet: {
		Method:      HttpGET,
		Path:        "/api/system/settings/:key",
		Label:       "配置详情",
		Description: "Get setting by key",
		Group:       "系统管理 - 系统配置 (Sys - Setting)",
	},
	SysSettingsUpdate: {
		Method:         HttpPUT,
		Path:           "/api/system/settings/:key",
		AuditAction:    "setting.update",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpUpdate,
		Label:          "更新配置",
		Description:    "Update setting",
		Group:          "系统管理 - 系统配置 (Sys - Setting)",
	},
	SysSettingsDelete: {
		Method:         HttpDELETE,
		Path:           "/api/system/settings/:key",
		AuditAction:    "setting.delete",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpDelete,
		Label:          "删除配置",
		Description:    "Delete setting",
		Group:          "系统管理 - 系统配置 (Sys - Setting)",
	},
	SysSettingsBatchUpdate: {
		Method:         HttpPOST,
		Path:           "/api/system/settings/batch",
		AuditAction:    "setting.batch_update",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpUpdate,
		Label:          "批量更新配置",
		Description:    "Batch update settings",
		Group:          "系统管理 - 系统配置 (Sys - Setting)",
	},

	// ==================== Sys 域 - 配置分类 ====================
	SysSettingCategoriesList: {
		Method:      HttpGET,
		Path:        "/api/system/settings/categories",
		Label:       "配置分类列表",
		Description: "List setting categories",
		Group:       "系统管理 - 系统配置 (Sys - Setting)",
	},
	SysSettingCategoriesGet: {
		Method:      HttpGET,
		Path:        "/api/system/settings/categories/:id",
		Label:       "配置分类详情",
		Description: "Get setting category by ID",
		Group:       "系统管理 - 系统配置 (Sys - Setting)",
	},
	SysSettingCategoriesCreate: {
		Method:         HttpPOST,
		Path:           "/api/system/settings/categories",
		AuditAction:    "setting_category.create",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpCreate,
		Label:          "创建配置分类",
		Description:    "Create setting category",
		Group:          "系统管理 - 系统配置 (Sys - Setting)",
	},
	SysSettingCategoriesUpdate: {
		Method:         HttpPUT,
		Path:           "/api/system/settings/categories/:id",
		AuditAction:    "setting_category.update",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpUpdate,
		Label:          "更新配置分类",
		Description:    "Update setting category",
		Group:          "系统管理 - 系统配置 (Sys - Setting)",
	},
	SysSettingCategoriesDelete: {
		Method:         HttpDELETE,
		Path:           "/api/system/settings/categories/:id",
		AuditAction:    "setting_category.delete",
		AuditCategory:  AuditCatSetting,
		AuditOperation: AuditOpDelete,
		Label:          "删除配置分类",
		Description:    "Delete setting category",
		Group:          "系统管理 - 系统配置 (Sys - Setting)",
	},

	// ==================== Sys 域 - 缓存管理 ====================
	SysCacheInfo: {
		Method:      HttpGET,
		Path:        "/api/system/cache/info",
		Label:       "缓存信息",
		Description: "Get cache info",
		Group:       "系统管理 - 缓存管理 (Sys - Cache)",
	},
	SysCacheScanKeys: {
		Method:      HttpGET,
		Path:        "/api/system/cache/keys",
		Label:       "扫描缓存键",
		Description: "Scan cache keys",
		Group:       "系统管理 - 缓存管理 (Sys - Cache)",
	},
	SysCacheGetKey: {
		Method:      HttpGET,
		Path:        "/api/system/cache/key",
		Label:       "获取缓存值",
		Description: "Get cache key value",
		Group:       "系统管理 - 缓存管理 (Sys - Cache)",
	},
	SysCacheDeleteKey: {
		Method:         HttpDELETE,
		Path:           "/api/system/cache/key",
		AuditAction:    "cache.delete",
		AuditCategory:  AuditCatCache,
		AuditOperation: AuditOpDelete,
		Label:          "删除缓存键",
		Description:    "Delete cache key",
		Group:          "系统管理 - 缓存管理 (Sys - Cache)",
	},
	SysCacheDeletePattern: {
		Method:         HttpDELETE,
		Path:           "/api/system/cache/keys",
		AuditAction:    "cache.delete_pattern",
		AuditCategory:  AuditCatCache,
		AuditOperation: AuditOpDelete,
		Label:          "批量删除缓存",
		Description:    "Delete cache keys by pattern",
		Group:          "系统管理 - 缓存管理 (Sys - Cache)",
	},

	// ==================== Self 域 - 个人资料 ====================
	SelfProfileGet: {
		Method:      HttpGET,
		Path:        "/api/user/profile",
		Label:       "获取资料",
		Description: "Get current user profile",
		Group:       "用户中心 - 个人资料 (User - Profile)",
	},
	SelfProfileUpdate: {
		Method:         HttpPUT,
		Path:           "/api/user/profile",
		AuditAction:    "profile.update",
		AuditCategory:  AuditCatProfile,
		AuditOperation: AuditOpUpdate,
		Label:          "更新资料",
		Description:    "Update current user profile",
		Group:          "用户中心 - 个人资料 (User - Profile)",
	},
	SelfPasswordUpdate: {
		Method:         HttpPUT,
		Path:           "/api/user/password",
		AuditAction:    "password.update",
		AuditCategory:  AuditCatProfile,
		AuditOperation: AuditOpUpdate,
		Label:          "修改密码",
		Description:    "Change password",
		Group:          "用户中心 - 个人资料 (User - Profile)",
	},
	SelfAccountDelete: {
		Method:         HttpDELETE,
		Path:           "/api/user/account",
		AuditAction:    "account.delete",
		AuditCategory:  AuditCatProfile,
		AuditOperation: AuditOpDelete,
		Label:          "注销账户",
		Description:    "Delete own account",
		Group:          "用户中心 - 个人资料 (User - Profile)",
	},

	// ==================== Self 域 - 访问令牌 ====================
	SelfTokensCreate: {
		Method:         HttpPOST,
		Path:           "/api/user/tokens",
		AuditAction:    "token.create",
		AuditCategory:  AuditCatToken,
		AuditOperation: AuditOpCreate,
		Label:          "创建令牌",
		Description:    "Create personal access token",
		Group:          "用户中心 - 访问令牌 (User - Token)",
	},
	SelfTokensList: {
		Method:      HttpGET,
		Path:        "/api/user/tokens",
		Label:       "令牌列表",
		Description: "List personal access tokens",
		Group:       "用户中心 - 访问令牌 (User - Token)",
	},
	SelfTokensGet: {
		Method:      HttpGET,
		Path:        "/api/user/tokens/:id",
		Label:       "令牌详情",
		Description: "Get token by ID",
		Group:       "用户中心 - 访问令牌 (User - Token)",
	},
	SelfTokensDelete: {
		Method:         HttpDELETE,
		Path:           "/api/user/tokens/:id",
		AuditAction:    "token.delete",
		AuditCategory:  AuditCatToken,
		AuditOperation: AuditOpDelete,
		Label:          "删除令牌",
		Description:    "Delete token",
		Group:          "用户中心 - 访问令牌 (User - Token)",
	},
	SelfTokensDisable: {
		Method:         HttpPATCH,
		Path:           "/api/user/tokens/:id/disable",
		AuditAction:    "token.disable",
		AuditCategory:  AuditCatToken,
		AuditOperation: AuditOpUpdate,
		Label:          "禁用令牌",
		Description:    "Disable token",
		Group:          "用户中心 - 访问令牌 (User - Token)",
	},
	SelfTokensEnable: {
		Method:         HttpPATCH,
		Path:           "/api/user/tokens/:id/enable",
		AuditAction:    "token.enable",
		AuditCategory:  AuditCatToken,
		AuditOperation: AuditOpUpdate,
		Label:          "启用令牌",
		Description:    "Enable token",
		Group:          "用户中心 - 访问令牌 (User - Token)",
	},

	// ==================== Self 域 - 用户配置 ====================
	SelfSettingsCategoriesList: {
		Method:      HttpGET,
		Path:        "/api/user/settings/categories",
		Label:       "配置分类列表",
		Description: "List user setting categories",
		Group:       "用户中心 - 用户配置 (User - Setting)",
	},
	SelfSettingsList: {
		Method:      HttpGET,
		Path:        "/api/user/settings",
		Label:       "用户配置列表",
		Description: "Get all user settings",
		Group:       "用户中心 - 用户配置 (User - Setting)",
	},
	SelfSettingsGet: {
		Method:      HttpGET,
		Path:        "/api/user/settings/:key",
		Label:       "用户配置详情",
		Description: "Get user setting by key",
		Group:       "用户中心 - 用户配置 (User - Setting)",
	},
	SelfSettingsSet: {
		Method:         HttpPUT,
		Path:           "/api/user/settings/:key",
		AuditAction:    "user_setting.set",
		AuditCategory:  AuditCatUserSetting,
		AuditOperation: AuditOpUpdate,
		Label:          "设置用户配置",
		Description:    "Set user setting",
		Group:          "用户中心 - 用户配置 (User - Setting)",
	},
	SelfSettingsReset: {
		Method:         HttpDELETE,
		Path:           "/api/user/settings/:key",
		AuditAction:    "user_setting.reset",
		AuditCategory:  AuditCatUserSetting,
		AuditOperation: AuditOpUpdate,
		Label:          "重置用户配置",
		Description:    "Reset user setting to default",
		Group:          "用户中心 - 用户配置 (User - Setting)",
	},
	SelfSettingsBatchSet: {
		Method:         HttpPOST,
		Path:           "/api/user/settings/batch",
		AuditAction:    "user_setting.batch_set",
		AuditCategory:  AuditCatUserSetting,
		AuditOperation: AuditOpUpdate,
		Label:          "批量设置配置",
		Description:    "Batch set user settings",
		Group:          "用户中心 - 用户配置 (User - Setting)",
	},
}
