package operation

// operationRegistry 操作注册表（单一数据源）
//
//nolint:gochecknoglobals // 注册表是只读全局配置
var operationRegistry = map[Operation]operationMeta{
	// ==================== Auth 域（公开） ====================
	AuthRegister: {
		Method:         HttpPOST,
		Path:           "/api/auth/register",
		AuditAction:    "auth.register",
		AuditCategory:  "auth",
		AuditOperation: AuditOpCreate,
		Label:          "注册",
		Description:    "User registration",
		Group:          "认证 (Auth)",
	},
	AuthLogin: {
		Method:         HttpPOST,
		Path:           "/api/auth/login",
		AuditAction:    "auth.login",
		AuditCategory:  "auth",
		AuditOperation: AuditOpAuthenticate,
		Label:          "登录",
		Description:    "User login",
		Group:          "认证 (Auth)",
	},
	AuthLogin2FA: {
		Method:         HttpPOST,
		Path:           "/api/auth/login/2fa",
		AuditAction:    "auth.login_2fa",
		AuditCategory:  "auth",
		AuditOperation: AuditOpAuthenticate,
		Label:          "2FA 登录",
		Description:    "Two-factor authentication login",
		Group:          "认证 (Auth)",
	},
	AuthRefresh: {
		Method:         HttpPOST,
		Path:           "/api/auth/refresh",
		AuditAction:    "auth.refresh",
		AuditCategory:  "auth",
		AuditOperation: AuditOpAuthenticate,
		Label:          "刷新令牌",
		Description:    "Refresh access token",
		Group:          "认证 (Auth)",
	},
	AuthCaptcha: {
		Method:      HttpGET,
		Path:        "/api/auth/captcha",
		Label:       "获取验证码",
		Description: "Get captcha image",
		Group:       "认证 (Auth)",
	},

	// ==================== Auth 域 - 2FA ====================
	Auth2FASetup: {
		Method:         HttpPOST,
		Path:           "/api/auth/2fa/setup",
		AuditAction:    "auth.2fa_setup",
		AuditCategory:  "auth",
		AuditOperation: AuditOpUpdate,
		Label:          "设置 2FA",
		Description:    "Setup two-factor authentication",
		Group:          "认证 - 2FA (Auth - 2FA)",
	},
	Auth2FAVerify: {
		Method:         HttpPOST,
		Path:           "/api/auth/2fa/verify",
		AuditAction:    "auth.2fa_enable",
		AuditCategory:  "auth",
		AuditOperation: AuditOpUpdate,
		Label:          "启用 2FA",
		Description:    "Verify and enable 2FA",
		Group:          "认证 - 2FA (Auth - 2FA)",
	},
	Auth2FADisable: {
		Method:         HttpPOST,
		Path:           "/api/auth/2fa/disable",
		AuditAction:    "auth.2fa_disable",
		AuditCategory:  "auth",
		AuditOperation: AuditOpUpdate,
		Label:          "禁用 2FA",
		Description:    "Disable two-factor authentication",
		Group:          "认证 - 2FA (Auth - 2FA)",
	},
	Auth2FAStatus: {
		Method:      HttpGET,
		Path:        "/api/auth/2fa/status",
		Label:       "2FA 状态",
		Description: "Get 2FA status",
		Group:       "认证 - 2FA (Auth - 2FA)",
	},

	// ==================== Admin 域 - 用户管理 ====================
	AdminUsersCreate: {
		Method:         HttpPOST,
		Path:           "/api/admin/users",
		Permission:     "admin:users:create",
		Role:           "admin",
		AuditAction:    "user.create",
		AuditCategory:  "user",
		AuditOperation: AuditOpCreate,
		Label:          "创建用户",
		Description:    "Create new user",
		Group:          "管理员 - 用户管理 (Admin - User)",
	},
	AdminUsersBatchCreate: {
		Method:         HttpPOST,
		Path:           "/api/admin/users/batch",
		Permission:     "admin:users:create",
		Role:           "admin",
		AuditAction:    "user.batch_create",
		AuditCategory:  "user",
		AuditOperation: AuditOpCreate,
		Label:          "批量创建用户",
		Description:    "Batch create users",
		Group:          "管理员 - 用户管理 (Admin - User)",
	},
	AdminUsersList: {
		Method:      HttpGET,
		Path:        "/api/admin/users",
		Permission:  "admin:users:read",
		Role:        "admin",
		Label:       "用户列表",
		Description: "List users",
		Group:       "管理员 - 用户管理 (Admin - User)",
	},
	AdminUsersGet: {
		Method:      HttpGET,
		Path:        "/api/admin/users/:id",
		Permission:  "admin:users:read",
		Role:        "admin",
		Label:       "用户详情",
		Description: "Get user by ID",
		Group:       "管理员 - 用户管理 (Admin - User)",
	},
	AdminUsersUpdate: {
		Method:         HttpPUT,
		Path:           "/api/admin/users/:id",
		Permission:     "admin:users:update",
		Role:           "admin",
		AuditAction:    "user.update",
		AuditCategory:  "user",
		AuditOperation: AuditOpUpdate,
		Label:          "更新用户",
		Description:    "Update user",
		Group:          "管理员 - 用户管理 (Admin - User)",
	},
	AdminUsersDelete: {
		Method:         HttpDELETE,
		Path:           "/api/admin/users/:id",
		Permission:     "admin:users:delete",
		Role:           "admin",
		AuditAction:    "user.delete",
		AuditCategory:  "user",
		AuditOperation: AuditOpDelete,
		Label:          "删除用户",
		Description:    "Delete user",
		Group:          "管理员 - 用户管理 (Admin - User)",
	},
	AdminUsersAssignRoles: {
		Method:         HttpPUT,
		Path:           "/api/admin/users/:id/roles",
		Permission:     "admin:users:update",
		Role:           "admin",
		AuditAction:    "user.assign_roles",
		AuditCategory:  "user",
		AuditOperation: AuditOpUpdate,
		Label:          "分配角色",
		Description:    "Assign roles to user",
		Group:          "管理员 - 用户管理 (Admin - User)",
	},

	// ==================== Admin 域 - 角色管理 ====================
	AdminRolesCreate: {
		Method:         HttpPOST,
		Path:           "/api/admin/roles",
		Permission:     "admin:roles:create",
		Role:           "admin",
		AuditAction:    "role.create",
		AuditCategory:  "role",
		AuditOperation: AuditOpCreate,
		Label:          "创建角色",
		Description:    "Create role",
		Group:          "管理员 - 角色管理 (Admin - Role)",
	},
	AdminRolesList: {
		Method:      HttpGET,
		Path:        "/api/admin/roles",
		Permission:  "admin:roles:read",
		Role:        "admin",
		Label:       "角色列表",
		Description: "List roles",
		Group:       "管理员 - 角色管理 (Admin - Role)",
	},
	AdminRolesGet: {
		Method:      HttpGET,
		Path:        "/api/admin/roles/:id",
		Permission:  "admin:roles:read",
		Role:        "admin",
		Label:       "角色详情",
		Description: "Get role by ID",
		Group:       "管理员 - 角色管理 (Admin - Role)",
	},
	AdminRolesUpdate: {
		Method:         HttpPUT,
		Path:           "/api/admin/roles/:id",
		Permission:     "admin:roles:update",
		Role:           "admin",
		AuditAction:    "role.update",
		AuditCategory:  "role",
		AuditOperation: AuditOpUpdate,
		Label:          "更新角色",
		Description:    "Update role",
		Group:          "管理员 - 角色管理 (Admin - Role)",
	},
	AdminRolesDelete: {
		Method:         HttpDELETE,
		Path:           "/api/admin/roles/:id",
		Permission:     "admin:roles:delete",
		Role:           "admin",
		AuditAction:    "role.delete",
		AuditCategory:  "role",
		AuditOperation: AuditOpDelete,
		Label:          "删除角色",
		Description:    "Delete role",
		Group:          "管理员 - 角色管理 (Admin - Role)",
	},
	AdminRolesSetPermissions: {
		Method:         HttpPUT,
		Path:           "/api/admin/roles/:id/permissions",
		Permission:     "admin:roles:update",
		Role:           "admin",
		AuditAction:    "role.set_permissions",
		AuditCategory:  "role",
		AuditOperation: AuditOpUpdate,
		Label:          "设置权限",
		Description:    "Set role permissions",
		Group:          "管理员 - 角色管理 (Admin - Role)",
	},

	// ==================== Admin 域 - 权限管理 ====================
	AdminPermissionsList: {
		Method:      HttpGET,
		Path:        "/api/admin/permissions",
		Permission:  "admin:permissions:read",
		Role:        "admin",
		Label:       "权限列表",
		Description: "List permissions",
		Group:       "管理员 - 权限管理 (Admin - Permission)",
	},

	// ==================== Admin 域 - 审计日志 ====================
	AdminAuditLogsList: {
		Method:      HttpGET,
		Path:        "/api/admin/auditlogs",
		Permission:  "admin:audit_logs:read",
		Role:        "admin",
		Label:       "审计日志列表",
		Description: "List audit logs",
		Group:       "管理员 - 审计日志 (Admin - Audit Log)",
	},
	AdminAuditLogsGet: {
		Method:      HttpGET,
		Path:        "/api/admin/auditlogs/:id",
		Permission:  "admin:audit_logs:read",
		Role:        "admin",
		Label:       "审计日志详情",
		Description: "Get audit log by ID",
		Group:       "管理员 - 审计日志 (Admin - Audit Log)",
	},
	AdminAuditLogsActions: {
		Method:      HttpGET,
		Path:        "/api/admin/auditlogs/actions",
		Permission:  "admin:audit_logs:read",
		Role:        "admin",
		Label:       "审计操作定义",
		Description: "Get audit action definitions",
		Group:       "管理员 - 审计日志 (Admin - Audit Log)",
	},

	// ==================== Admin 域 - 菜单管理 ====================
	AdminMenusCreate: {
		Method:         HttpPOST,
		Path:           "/api/admin/menus",
		Permission:     "admin:menus:create",
		Role:           "admin",
		AuditAction:    "menu.create",
		AuditCategory:  "menu",
		AuditOperation: AuditOpCreate,
		Label:          "创建菜单",
		Description:    "Create menu",
		Group:          "管理员 - 菜单管理 (Admin - Menu)",
	},
	AdminMenusList: {
		Method:      HttpGET,
		Path:        "/api/admin/menus",
		Permission:  "admin:menus:read",
		Role:        "admin",
		Label:       "菜单列表",
		Description: "List menus",
		Group:       "管理员 - 菜单管理 (Admin - Menu)",
	},
	AdminMenusGet: {
		Method:      HttpGET,
		Path:        "/api/admin/menus/:id",
		Permission:  "admin:menus:read",
		Role:        "admin",
		Label:       "菜单详情",
		Description: "Get menu by ID",
		Group:       "管理员 - 菜单管理 (Admin - Menu)",
	},
	AdminMenusUpdate: {
		Method:         HttpPUT,
		Path:           "/api/admin/menus/:id",
		Permission:     "admin:menus:update",
		Role:           "admin",
		AuditAction:    "menu.update",
		AuditCategory:  "menu",
		AuditOperation: AuditOpUpdate,
		Label:          "更新菜单",
		Description:    "Update menu",
		Group:          "管理员 - 菜单管理 (Admin - Menu)",
	},
	AdminMenusDelete: {
		Method:         HttpDELETE,
		Path:           "/api/admin/menus/:id",
		Permission:     "admin:menus:delete",
		Role:           "admin",
		AuditAction:    "menu.delete",
		AuditCategory:  "menu",
		AuditOperation: AuditOpDelete,
		Label:          "删除菜单",
		Description:    "Delete menu",
		Group:          "管理员 - 菜单管理 (Admin - Menu)",
	},
	AdminMenusReorder: {
		Method:         HttpPOST,
		Path:           "/api/admin/menus/reorder",
		Permission:     "admin:menus:update",
		Role:           "admin",
		AuditAction:    "menu.reorder",
		AuditCategory:  "menu",
		AuditOperation: AuditOpUpdate,
		Label:          "重排菜单",
		Description:    "Reorder menus",
		Group:          "管理员 - 菜单管理 (Admin - Menu)",
	},

	// ==================== Admin 域 - 系统概览 ====================
	AdminOverviewStats: {
		Method:      HttpGET,
		Path:        "/api/admin/overview/stats",
		Permission:  "admin:overview:read",
		Role:        "admin",
		Label:       "系统概览",
		Description: "Get system overview stats",
		Group:       "管理员 - 系统概览 (Admin - Overview)",
	},

	// ==================== Admin 域 - 系统配置 ====================
	AdminSettingsCreate: {
		Method:         HttpPOST,
		Path:           "/api/admin/settings",
		Permission:     "admin:settings:create",
		Role:           "admin",
		AuditAction:    "setting.create",
		AuditCategory:  "setting",
		AuditOperation: AuditOpCreate,
		Label:          "创建配置",
		Description:    "Create setting",
		Group:          "管理员 - 系统配置 (Admin - Setting)",
	},
	AdminSettingsList: {
		Method:      HttpGET,
		Path:        "/api/admin/settings",
		Permission:  "admin:settings:read",
		Role:        "admin",
		Label:       "配置列表",
		Description: "List settings",
		Group:       "管理员 - 系统配置 (Admin - Setting)",
	},
	AdminSettingsGet: {
		Method:      HttpGET,
		Path:        "/api/admin/settings/:key",
		Permission:  "admin:settings:read",
		Role:        "admin",
		Label:       "配置详情",
		Description: "Get setting by key",
		Group:       "管理员 - 系统配置 (Admin - Setting)",
	},
	AdminSettingsUpdate: {
		Method:         HttpPUT,
		Path:           "/api/admin/settings/:key",
		Permission:     "admin:settings:update",
		Role:           "admin",
		AuditAction:    "setting.update",
		AuditCategory:  "setting",
		AuditOperation: AuditOpUpdate,
		Label:          "更新配置",
		Description:    "Update setting",
		Group:          "管理员 - 系统配置 (Admin - Setting)",
	},
	AdminSettingsDelete: {
		Method:         HttpDELETE,
		Path:           "/api/admin/settings/:key",
		Permission:     "admin:settings:delete",
		Role:           "admin",
		AuditAction:    "setting.delete",
		AuditCategory:  "setting",
		AuditOperation: AuditOpDelete,
		Label:          "删除配置",
		Description:    "Delete setting",
		Group:          "管理员 - 系统配置 (Admin - Setting)",
	},
	AdminSettingsBatchUpdate: {
		Method:         HttpPOST,
		Path:           "/api/admin/settings/batch",
		Permission:     "admin:settings:update",
		Role:           "admin",
		AuditAction:    "setting.batch_update",
		AuditCategory:  "setting",
		AuditOperation: AuditOpUpdate,
		Label:          "批量更新配置",
		Description:    "Batch update settings",
		Group:          "管理员 - 系统配置 (Admin - Setting)",
	},

	// ==================== Admin 域 - 配置分类 ====================
	AdminSettingCategoriesList: {
		Method:      HttpGET,
		Path:        "/api/admin/settings/categories",
		Permission:  "admin:settings:read",
		Role:        "admin",
		Label:       "配置分类列表",
		Description: "List setting categories",
		Group:       "管理员 - 系统配置 (Admin - Setting)",
	},
	AdminSettingCategoriesGet: {
		Method:      HttpGET,
		Path:        "/api/admin/settings/categories/:id",
		Permission:  "admin:settings:read",
		Role:        "admin",
		Label:       "配置分类详情",
		Description: "Get setting category by ID",
		Group:       "管理员 - 系统配置 (Admin - Setting)",
	},
	AdminSettingCategoriesCreate: {
		Method:         HttpPOST,
		Path:           "/api/admin/settings/categories",
		Permission:     "admin:settings:create",
		Role:           "admin",
		AuditAction:    "setting_category.create",
		AuditCategory:  "setting",
		AuditOperation: AuditOpCreate,
		Label:          "创建配置分类",
		Description:    "Create setting category",
		Group:          "管理员 - 系统配置 (Admin - Setting)",
	},
	AdminSettingCategoriesUpdate: {
		Method:         HttpPUT,
		Path:           "/api/admin/settings/categories/:id",
		Permission:     "admin:settings:update",
		Role:           "admin",
		AuditAction:    "setting_category.update",
		AuditCategory:  "setting",
		AuditOperation: AuditOpUpdate,
		Label:          "更新配置分类",
		Description:    "Update setting category",
		Group:          "管理员 - 系统配置 (Admin - Setting)",
	},
	AdminSettingCategoriesDelete: {
		Method:         HttpDELETE,
		Path:           "/api/admin/settings/categories/:id",
		Permission:     "admin:settings:delete",
		Role:           "admin",
		AuditAction:    "setting_category.delete",
		AuditCategory:  "setting",
		AuditOperation: AuditOpDelete,
		Label:          "删除配置分类",
		Description:    "Delete setting category",
		Group:          "管理员 - 系统配置 (Admin - Setting)",
	},

	// ==================== Admin 域 - 缓存管理 ====================
	AdminCacheInfo: {
		Method:      HttpGET,
		Path:        "/api/admin/cache/info",
		Permission:  "admin:cache:read",
		Role:        "admin",
		Label:       "缓存信息",
		Description: "Get cache info",
		Group:       "管理员 - 缓存管理 (Admin - Cache)",
	},
	AdminCacheScanKeys: {
		Method:      HttpGET,
		Path:        "/api/admin/cache/keys",
		Permission:  "admin:cache:read",
		Role:        "admin",
		Label:       "扫描缓存键",
		Description: "Scan cache keys",
		Group:       "管理员 - 缓存管理 (Admin - Cache)",
	},
	AdminCacheGetKey: {
		Method:      HttpGET,
		Path:        "/api/admin/cache/key",
		Permission:  "admin:cache:read",
		Role:        "admin",
		Label:       "获取缓存值",
		Description: "Get cache key value",
		Group:       "管理员 - 缓存管理 (Admin - Cache)",
	},
	AdminCacheDeleteKey: {
		Method:         HttpDELETE,
		Path:           "/api/admin/cache/key",
		Permission:     "admin:cache:delete",
		Role:           "admin",
		AuditAction:    "cache.delete",
		AuditCategory:  "cache",
		AuditOperation: AuditOpDelete,
		Label:          "删除缓存键",
		Description:    "Delete cache key",
		Group:          "管理员 - 缓存管理 (Admin - Cache)",
	},
	AdminCacheDeletePattern: {
		Method:         HttpDELETE,
		Path:           "/api/admin/cache/keys",
		Permission:     "admin:cache:delete",
		Role:           "admin",
		AuditAction:    "cache.delete_pattern",
		AuditCategory:  "cache",
		AuditOperation: AuditOpDelete,
		Label:          "批量删除缓存",
		Description:    "Delete cache keys by pattern",
		Group:          "管理员 - 缓存管理 (Admin - Cache)",
	},

	// ==================== User 域 - 个人资料 ====================
	UserProfileGet: {
		Method:      HttpGET,
		Path:        "/api/user/profile",
		Permission:  "user:profile:read",
		Label:       "获取资料",
		Description: "Get current user profile",
		Group:       "用户中心 - 个人资料 (User - Profile)",
	},
	UserProfileUpdate: {
		Method:         HttpPUT,
		Path:           "/api/user/profile",
		Permission:     "user:profile:update",
		AuditAction:    "profile.update",
		AuditCategory:  "profile",
		AuditOperation: AuditOpUpdate,
		Label:          "更新资料",
		Description:    "Update current user profile",
		Group:          "用户中心 - 个人资料 (User - Profile)",
	},
	UserPasswordUpdate: {
		Method:         HttpPUT,
		Path:           "/api/user/password",
		Permission:     "user:password:update",
		AuditAction:    "password.update",
		AuditCategory:  "profile",
		AuditOperation: AuditOpUpdate,
		Label:          "修改密码",
		Description:    "Change password",
		Group:          "用户中心 - 个人资料 (User - Profile)",
	},
	UserAccountDelete: {
		Method:         HttpDELETE,
		Path:           "/api/user/account",
		Permission:     "user:profile:delete",
		AuditAction:    "account.delete",
		AuditCategory:  "profile",
		AuditOperation: AuditOpDelete,
		Label:          "注销账户",
		Description:    "Delete own account",
		Group:          "用户中心 - 个人资料 (User - Profile)",
	},

	// ==================== User 域 - 访问令牌 ====================
	UserTokensCreate: {
		Method:         HttpPOST,
		Path:           "/api/user/tokens",
		Permission:     "user:tokens:create",
		AuditAction:    "token.create",
		AuditCategory:  "token",
		AuditOperation: AuditOpCreate,
		Label:          "创建令牌",
		Description:    "Create personal access token",
		Group:          "用户中心 - 访问令牌 (User - Token)",
	},
	UserTokensList: {
		Method:      HttpGET,
		Path:        "/api/user/tokens",
		Permission:  "user:tokens:read",
		Label:       "令牌列表",
		Description: "List personal access tokens",
		Group:       "用户中心 - 访问令牌 (User - Token)",
	},
	UserTokensGet: {
		Method:      HttpGET,
		Path:        "/api/user/tokens/:id",
		Permission:  "user:tokens:read",
		Label:       "令牌详情",
		Description: "Get token by ID",
		Group:       "用户中心 - 访问令牌 (User - Token)",
	},
	UserTokensDelete: {
		Method:         HttpDELETE,
		Path:           "/api/user/tokens/:id",
		Permission:     "user:tokens:delete",
		AuditAction:    "token.delete",
		AuditCategory:  "token",
		AuditOperation: AuditOpDelete,
		Label:          "删除令牌",
		Description:    "Delete token",
		Group:          "用户中心 - 访问令牌 (User - Token)",
	},
	UserTokensDisable: {
		Method:         HttpPATCH,
		Path:           "/api/user/tokens/:id/disable",
		Permission:     "user:tokens:disable",
		AuditAction:    "token.disable",
		AuditCategory:  "token",
		AuditOperation: AuditOpUpdate,
		Label:          "禁用令牌",
		Description:    "Disable token",
		Group:          "用户中心 - 访问令牌 (User - Token)",
	},
	UserTokensEnable: {
		Method:         HttpPATCH,
		Path:           "/api/user/tokens/:id/enable",
		Permission:     "user:tokens:enable",
		AuditAction:    "token.enable",
		AuditCategory:  "token",
		AuditOperation: AuditOpUpdate,
		Label:          "启用令牌",
		Description:    "Enable token",
		Group:          "用户中心 - 访问令牌 (User - Token)",
	},

	// ==================== User 域 - 用户配置 ====================
	UserSettingsCategoriesList: {
		Method:      HttpGET,
		Path:        "/api/user/settings/categories",
		Permission:  "user:settings:read",
		Label:       "配置分类列表",
		Description: "List user setting categories",
		Group:       "用户中心 - 用户配置 (User - Setting)",
	},
	UserSettingsList: {
		Method:      HttpGET,
		Path:        "/api/user/settings",
		Permission:  "user:settings:read",
		Label:       "用户配置列表",
		Description: "Get all user settings",
		Group:       "用户中心 - 用户配置 (User - Setting)",
	},
	UserSettingsGet: {
		Method:      HttpGET,
		Path:        "/api/user/settings/:key",
		Permission:  "user:settings:read",
		Label:       "用户配置详情",
		Description: "Get user setting by key",
		Group:       "用户中心 - 用户配置 (User - Setting)",
	},
	UserSettingsSet: {
		Method:         HttpPUT,
		Path:           "/api/user/settings/:key",
		Permission:     "user:settings:update",
		AuditAction:    "user_setting.set",
		AuditCategory:  "user_setting",
		AuditOperation: AuditOpUpdate,
		Label:          "设置用户配置",
		Description:    "Set user setting",
		Group:          "用户中心 - 用户配置 (User - Setting)",
	},
	UserSettingsReset: {
		Method:         HttpDELETE,
		Path:           "/api/user/settings/:key",
		Permission:     "user:settings:update",
		AuditAction:    "user_setting.reset",
		AuditCategory:  "user_setting",
		AuditOperation: AuditOpUpdate,
		Label:          "重置用户配置",
		Description:    "Reset user setting to default",
		Group:          "用户中心 - 用户配置 (User - Setting)",
	},
	UserSettingsBatchSet: {
		Method:         HttpPOST,
		Path:           "/api/user/settings/batch",
		Permission:     "user:settings:update",
		AuditAction:    "user_setting.batch_set",
		AuditCategory:  "user_setting",
		AuditOperation: AuditOpUpdate,
		Label:          "批量设置配置",
		Description:    "Batch set user settings",
		Group:          "用户中心 - 用户配置 (User - Setting)",
	},
}
