/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BREAKPOINTS: typeof import("./composables/useWindowSize").BREAKPOINTS;
  const DISTANCE_UNITS: typeof import("./composables/useGeolocation").DISTANCE_UNITS;
  const EffectScope: typeof import("vue").EffectScope;
  const acceptHMRUpdate: typeof import("pinia").acceptHMRUpdate;
  const appEventBus: typeof import("./composables/useEventBus").appEventBus;
  const calculateDistance: typeof import("./composables/useGeolocation").calculateDistance;
  const clearFetchCache: typeof import("./composables/useFetch").clearFetchCache;
  const clearSWRCache: typeof import("./composables/useSWR").clearSWRCache;
  const clearStorageByPrefix: typeof import("./composables/useStorage").clearStorageByPrefix;
  const commonShortcuts: typeof import("./composables/useKeyboard").commonShortcuts;
  const computed: typeof import("vue").computed;
  const computedArray: typeof import("./composables/useComputed").computedArray;
  const computedAsync: typeof import("./composables/useComputed").computedAsync;
  const computedDebounced: typeof import("./composables/useComputed").computedDebounced;
  const computedDefault: typeof import("./composables/useComputed").computedDefault;
  const computedDelayed: typeof import("./composables/useComputed").computedDelayed;
  const computedEager: typeof import("./composables/useComputed").computedEager;
  const computedFilter: typeof import("./composables/useComputed").computedFilter;
  const computedFind: typeof import("./composables/useComputed").computedFind;
  const computedFrom: typeof import("./composables/useComputed").computedFrom;
  const computedGroupBy: typeof import("./composables/useComputed").computedGroupBy;
  const computedIf: typeof import("./composables/useComputed").computedIf;
  const computedMap: typeof import("./composables/useComputed").computedMap;
  const computedObject: typeof import("./composables/useComputed").computedObject;
  const computedOmit: typeof import("./composables/useComputed").computedOmit;
  const computedPick: typeof import("./composables/useComputed").computedPick;
  const computedSort: typeof import("./composables/useComputed").computedSort;
  const computedThrottled: typeof import("./composables/useComputed").computedThrottled;
  const computedWithControl: typeof import("./composables/useComputed").computedWithControl;
  const computedWithHistory: typeof import("./composables/useComputed").computedWithHistory;
  const createApp: typeof import("vue").createApp;
  const createContext: typeof import("./composables/useProvide").createContext;
  const createEventBus: typeof import("./composables/useEventBus").createEventBus;
  const createEventBusContext: typeof import("./composables/useProvide").createEventBusContext;
  const createEventSourceManager: typeof import("./composables/useEventSource").createEventSourceManager;
  const createFactoryContext: typeof import("./composables/useProvide").createFactoryContext;
  const createFetch: typeof import("./composables/useFetch").createFetch;
  const createI18nContext: typeof import("./composables/useProvide").createI18nContext;
  const createPinia: typeof import("pinia").createPinia;
  const createReactiveContext: typeof import("./composables/useProvide").createReactiveContext;
  const createReadonlyContext: typeof import("./composables/useProvide").createReadonlyContext;
  const createStateContext: typeof import("./composables/useProvide").createStateContext;
  const createStorageContext: typeof import("./composables/useProvide").createStorageContext;
  const createThemeContext: typeof import("./composables/useProvide").createThemeContext;
  const createWebSocketManager: typeof import("./composables/useWebSocket").createWebSocketManager;
  const customRef: typeof import("vue").customRef;
  const decimalToDms: typeof import("./composables/useGeolocation").decimalToDms;
  const deepClone: typeof import("./composables/useClone").deepClone;
  const defineAsyncComponent: typeof import("vue").defineAsyncComponent;
  const defineComponent: typeof import("vue").defineComponent;
  const defineStore: typeof import("pinia").defineStore;
  const deleteFetchCache: typeof import("./composables/useFetch").deleteFetchCache;
  const deleteSWRCache: typeof import("./composables/useSWR").deleteSWRCache;
  const dmsToDecimal: typeof import("./composables/useGeolocation").dmsToDecimal;
  const effectScope: typeof import("vue").effectScope;
  const formatCoordinates: typeof import("./composables/useGeolocation").formatCoordinates;
  const formatDistance: typeof import("./composables/useGeolocation").formatDistance;
  const formatDuration: typeof import("./composables/useMedia").formatDuration;
  const getActivePinia: typeof import("pinia").getActivePinia;
  const getAppleMapsUrl: typeof import("./composables/useGeolocation").getAppleMapsUrl;
  const getCurrentInstance: typeof import("vue").getCurrentInstance;
  const getCurrentScope: typeof import("vue").getCurrentScope;
  const getCurrentWatcher: typeof import("vue").getCurrentWatcher;
  const getDragItemClasses: typeof import("./composables/useDraggable").getDragItemClasses;
  const getFetchCacheSize: typeof import("./composables/useFetch").getFetchCacheSize;
  const getGlobalEventBus: typeof import("./composables/useEventBus").getGlobalEventBus;
  const getGoogleMapsUrl: typeof import("./composables/useGeolocation").getGoogleMapsUrl;
  const getNavigationUrl: typeof import("./composables/useGeolocation").getNavigationUrl;
  const getSWRCache: typeof import("./composables/useSWR").getSWRCache;
  const h: typeof import("vue").h;
  const inject: typeof import("vue").inject;
  const isPermissionsApiSupported: typeof import("./composables/usePermission").isPermissionsApiSupported;
  const isProxy: typeof import("vue").isProxy;
  const isReactive: typeof import("vue").isReactive;
  const isReadonly: typeof import("vue").isReadonly;
  const isRef: typeof import("vue").isRef;
  const isShallow: typeof import("vue").isShallow;
  const mapActions: typeof import("pinia").mapActions;
  const mapGetters: typeof import("pinia").mapGetters;
  const mapState: typeof import("pinia").mapState;
  const mapStores: typeof import("pinia").mapStores;
  const mapWritableState: typeof import("pinia").mapWritableState;
  const markRaw: typeof import("vue").markRaw;
  const nextTick: typeof import("vue").nextTick;
  const onActivated: typeof import("vue").onActivated;
  const onBeforeMount: typeof import("vue").onBeforeMount;
  const onBeforeRouteLeave: typeof import("vue-router").onBeforeRouteLeave;
  const onBeforeRouteUpdate: typeof import("vue-router").onBeforeRouteUpdate;
  const onBeforeUnmount: typeof import("vue").onBeforeUnmount;
  const onBeforeUpdate: typeof import("vue").onBeforeUpdate;
  const onDeactivated: typeof import("vue").onDeactivated;
  const onErrorCaptured: typeof import("vue").onErrorCaptured;
  const onMounted: typeof import("vue").onMounted;
  const onRenderTracked: typeof import("vue").onRenderTracked;
  const onRenderTriggered: typeof import("vue").onRenderTriggered;
  const onScopeDispose: typeof import("vue").onScopeDispose;
  const onServerPrefetch: typeof import("vue").onServerPrefetch;
  const onUnmounted: typeof import("vue").onUnmounted;
  const onUpdated: typeof import("vue").onUpdated;
  const onWatcherCleanup: typeof import("vue").onWatcherCleanup;
  const provide: typeof import("vue").provide;
  const queryPermissions: typeof import("./composables/usePermission").queryPermissions;
  const reactive: typeof import("vue").reactive;
  const reactiveDefault: typeof import("./composables/useReactive").reactiveDefault;
  const reactiveExtend: typeof import("./composables/useReactive").reactiveExtend;
  const reactiveForm: typeof import("./composables/useReactive").reactiveForm;
  const reactiveHistory: typeof import("./composables/useReactive").reactiveHistory;
  const reactiveMerge: typeof import("./composables/useReactive").reactiveMerge;
  const reactiveOmit: typeof import("./composables/useReactive").reactiveOmit;
  const reactivePick: typeof import("./composables/useReactive").reactivePick;
  const reactiveResettable: typeof import("./composables/useReactive").reactiveResettable;
  const reactiveTransform: typeof import("./composables/useReactive").reactiveTransform;
  const reactiveUtils: typeof import("./composables/useReactive").reactiveUtils;
  const reactiveValidated: typeof import("./composables/useReactive").reactiveValidated;
  const reactiveWhen: typeof import("./composables/useReactive").reactiveWhen;
  const reactiveWithOptions: typeof import("./composables/useReactive").reactiveWithOptions;
  const reactiveWithReadonly: typeof import("./composables/useReactive").reactiveWithReadonly;
  const readonly: typeof import("vue").readonly;
  const ref: typeof import("vue").ref;
  const refAutoReset: typeof import("./composables/useRef").refAutoReset;
  const refDebounced: typeof import("./composables/useRef").refDebounced;
  const refDefault: typeof import("./composables/useRef").refDefault;
  const refHistory: typeof import("./composables/useRef").refHistory;
  const refLocked: typeof import("./composables/useRef").refLocked;
  const refThrottled: typeof import("./composables/useRef").refThrottled;
  const refWithControl: typeof import("./composables/useRef").refWithControl;
  const resolveComponent: typeof import("vue").resolveComponent;
  const revalidateSWR: typeof import("./composables/useSWR").revalidateSWR;
  const setActivePinia: typeof import("pinia").setActivePinia;
  const setMapStoreSuffix: typeof import("pinia").setMapStoreSuffix;
  const setSWRCache: typeof import("./composables/useSWR").setSWRCache;
  const shallowReactive: typeof import("vue").shallowReactive;
  const shallowReadonly: typeof import("vue").shallowReadonly;
  const shallowRef: typeof import("vue").shallowRef;
  const storeToRefs: typeof import("pinia").storeToRefs;
  const structuredClonePolyfill: typeof import("./composables/useClone").structuredClonePolyfill;
  const syncReactive: typeof import("./composables/useReactive").syncReactive;
  const syncRefs: typeof import("./composables/useRef").syncRefs;
  const templateRef: typeof import("./composables/useRef").templateRef;
  const toComputed: typeof import("./composables/useComputed").toComputed;
  const toRaw: typeof import("vue").toRaw;
  const toRef: typeof import("vue").toRef;
  const toRefs: typeof import("vue").toRefs;
  const toValue: typeof import("vue").toValue;
  const triggerRef: typeof import("vue").triggerRef;
  const unref: typeof import("vue").unref;
  const until: typeof import("./composables/useWatch").until;
  const useActivated: typeof import("./composables/useLifecycle").useActivated;
  const useAnimateOnScroll: typeof import("./composables/useIntersectionObserver").useAnimateOnScroll;
  const useAnimation: typeof import("./composables/useTransition").useAnimation;
  const useAppEventBus: typeof import("./composables/useEventBus").useAppEventBus;
  const useArray: typeof import("./composables/useRef").useArray;
  const useAsyncMounted: typeof import("./composables/useLifecycle").useAsyncMounted;
  const useAsyncRef: typeof import("./composables/useAsync").useAsyncRef;
  const useAsyncRetry: typeof import("./composables/useAsync").useAsyncRetry;
  const useAsyncState: typeof import("./composables/useAsync").useAsyncState;
  const useAttrs: typeof import("vue").useAttrs;
  const useAttrsEnhanced: typeof import("./composables/useComponent").useAttrsEnhanced;
  const useAudio: typeof import("./composables/useMedia").useAudio;
  const useAudioVisualizer: typeof import("./composables/useMedia").useAudioVisualizer;
  const useAuthStore: typeof import("@/stores/auth").useAuthStore;
  const useAutoFocus: typeof import("./composables/useFocusTrap").useAutoFocus;
  const useBoolean: typeof import("./composables/useRef").useBoolean;
  const useBroadcastChannel: typeof import("./composables/useBroadcastChannel").useBroadcastChannel;
  const useBroadcastChannelJSON: typeof import("./composables/useBroadcastChannel").useBroadcastChannelJSON;
  const useCameraPermission: typeof import("./composables/usePermission").useCameraPermission;
  const useCanHover: typeof import("./composables/useWindowSize").useCanHover;
  const useClassMerge: typeof import("./composables/useComponent").useClassMerge;
  const useCleanup: typeof import("./composables/useLifecycle").useCleanup;
  const useClickOutside: typeof import("./composables/useClickOutside").useClickOutside;
  const useClickOutsideToggle: typeof import("./composables/useClickOutside").useClickOutsideToggle;
  const useClipboard: typeof import("./composables/useClipboard").useClipboard;
  const useClipboardPermission: typeof import("./composables/usePermission").useClipboardPermission;
  const useCloned: typeof import("./composables/useClone").useCloned;
  const useColorMode: typeof import("./composables/usePreferences").useColorMode;
  const useComponentAliveTime: typeof import("./composables/useLifecycle").useComponentAliveTime;
  const useComponentEmit: typeof import("./composables/useComponent").useComponentEmit;
  const useComponentInfo: typeof import("./composables/useComponent").useComponentInfo;
  const useComponentProxy: typeof import("./composables/useComponent").useComponentProxy;
  const useComponentRef: typeof import("./composables/useComponent").useComponentRef;
  const useComponentRefs: typeof import("./composables/useComponent").useComponentRefs;
  const useComponentType: typeof import("./composables/useComponent").useComponentType;
  const useComponentVisible: typeof import("./composables/useLifecycle").useComponentVisible;
  const useConditionalSlot: typeof import("./composables/useComponent").useConditionalSlot;
  const useConfirm: typeof import("./composables/useConfirm").useConfirm;
  const useControlled: typeof import("./composables/useVModel").useControlled;
  const useCountdown: typeof import("./composables/useCountdown").useCountdown;
  const useCounter: typeof import("./composables/useRef").useCounter;
  const useCssModule: typeof import("vue").useCssModule;
  const useCssVars: typeof import("vue").useCssVars;
  const useCursor: typeof import("./composables/useMouse").useCursor;
  const useCustomProperties: typeof import("./composables/useComponent").useCustomProperties;
  const useCycleList: typeof import("./composables/useVModel").useCycleList;
  const useDark: typeof import("./composables/usePreferences").useDark;
  const useDateFormat: typeof import("./composables/useTimer").useDateFormat;
  const useDeactivated: typeof import("./composables/useLifecycle").useDeactivated;
  const useDebounceFn: typeof import("./composables/useDebounce").useDebounceFn;
  const useDebouncedRef: typeof import("./composables/useDebounce").useDebouncedRef;
  const useDebouncedVModel: typeof import("./composables/useVModel").useDebouncedVModel;
  const useDirtyState: typeof import("./composables/useClone").useDirtyState;
  const useDocumentFullscreen: typeof import("./composables/useFullscreen").useDocumentFullscreen;
  const useDocumentTitle: typeof import("./composables/useTitle").useDocumentTitle;
  const useDocumentVisibility: typeof import("./composables/useTitle").useDocumentVisibility;
  const useDropZone: typeof import("./composables/useMouse").useDropZone;
  const useElementScrollLock: typeof import("./composables/useScrollLock").useElementScrollLock;
  const useElementSize: typeof import("./composables/useWindowSize").useElementSize;
  const useErrorCapture: typeof import("./composables/useLifecycle").useErrorCapture;
  const useEventBus: typeof import("./composables/useEventBus").useEventBus;
  const useEventListener: typeof import("./composables/useEventBus").useEventListener;
  const useEventSource: typeof import("./composables/useEventSource").useEventSource;
  const useEventSourceNamed: typeof import("./composables/useEventSource").useEventSourceNamed;
  const useEventValue: typeof import("./composables/useEventBus").useEventValue;
  const useExposeMethod: typeof import("./composables/useComponent").useExposeMethod;
  const useExposeState: typeof import("./composables/useComponent").useExposeState;
  const useFade: typeof import("./composables/useTransition").useFade;
  const useFavicon: typeof import("./composables/useTitle").useFavicon;
  const useFetch: typeof import("./composables/useFetch").useFetch;
  const useFieldArray: typeof import("./composables/useForm").useFieldArray;
  const useFileDrop: typeof import("./composables/useDraggable").useFileDrop;
  const useFocusReturn: typeof import("./composables/useFocusTrap").useFocusReturn;
  const useFocusTrap: typeof import("./composables/useFocusTrap").useFocusTrap;
  const useFocusTrapWhenTrue: typeof import("./composables/useFocusTrap").useFocusTrapWhenTrue;
  const useForceUpdate: typeof import("./composables/useComponent").useForceUpdate;
  const useForm: typeof import("./composables/useForm").useForm;
  const useFormDirtyGuard: typeof import("./composables/useForm").useFormDirtyGuard;
  const useFullscreen: typeof import("./composables/useFullscreen").useFullscreen;
  const useFullscreenButton: typeof import("./composables/useFullscreen").useFullscreenButton;
  const useGeolocation: typeof import("./composables/useGeolocation").useGeolocation;
  const useGeolocationBounds: typeof import("./composables/useGeolocation").useGeolocationBounds;
  const useGeolocationPermission: typeof import("./composables/usePermission").useGeolocationPermission;
  const useGeolocationWatch: typeof import("./composables/useGeolocation").useGeolocationWatch;
  const useHead: typeof import("./composables/useTitle").useHead;
  const useHistory: typeof import("./composables/useHistory").useHistory;
  const useHistoryQueue: typeof import("./composables/useQueue").useHistoryQueue;
  const useHover: typeof import("./composables/useMouse").useHover;
  const useId: typeof import("vue").useId;
  const useIdleCallback: typeof import("./composables/useTimer").useIdleCallback;
  const useImage: typeof import("./composables/useImage").useImage;
  const useImageCompression: typeof import("./composables/useImage").useImageCompression;
  const useImagePreload: typeof import("./composables/useImage").useImagePreload;
  const useInfiniteFetch: typeof import("./composables/useFetch").useInfiniteFetch;
  const useInfiniteScroll: typeof import("./composables/useIntersectionObserver").useInfiniteScroll;
  const useInstance: typeof import("./composables/useLifecycle").useInstance;
  const useIntersectionObserver: typeof import("./composables/useIntersectionObserver").useIntersectionObserver;
  const useInterval: typeof import("./composables/useTimer").useInterval;
  const useIntervalFn: typeof import("./composables/useTimer").useIntervalFn;
  const useIsRetina: typeof import("./composables/useWindowSize").useIsRetina;
  const useIsTouchDevice: typeof import("./composables/useWindowSize").useIsTouchDevice;
  const useKeyboard: typeof import("./composables/useKeyboard").useKeyboard;
  const useLatest: typeof import("./composables/useRef").useLatest;
  const useLazyFetch: typeof import("./composables/useFetch").useLazyFetch;
  const useLazyImage: typeof import("./composables/useImage").useLazyImage;
  const useLazyLoad: typeof import("./composables/useIntersectionObserver").useLazyLoad;
  const useLifecycle: typeof import("./composables/useLifecycle").useLifecycle;
  const useLifecycleTracker: typeof import("./composables/useLifecycle").useLifecycleTracker;
  const useLink: typeof import("vue-router").useLink;
  const useLocalStorage: typeof import("./composables/useStorage").useLocalStorage;
  const useManualClone: typeof import("./composables/useClone").useManualClone;
  const useManualHistory: typeof import("./composables/useHistory").useManualHistory;
  const useMap: typeof import("./composables/useRef").useMap;
  const useMedia: typeof import("./composables/useMedia").useMedia;
  const useMediaQuery: typeof import("./composables/useWindowSize").useMediaQuery;
  const useMemoize: typeof import("./composables/useClone").useMemoize;
  const useMicrophonePermission: typeof import("./composables/usePermission").useMicrophonePermission;
  const useModel: typeof import("vue").useModel;
  const useModelValue: typeof import("./composables/useVModel").useModelValue;
  const useMounted: typeof import("./composables/useLifecycle").useMounted;
  const useMountedDelay: typeof import("./composables/useLifecycle").useMountedDelay;
  const useMountedNextFrame: typeof import("./composables/useLifecycle").useMountedNextFrame;
  const useMountedNextTick: typeof import("./composables/useLifecycle").useMountedNextTick;
  const useMountedOnce: typeof import("./composables/useLifecycle").useMountedOnce;
  const useMountedOrActivated: typeof import("./composables/useLifecycle").useMountedOrActivated;
  const useMountedState: typeof import("./composables/useLifecycle").useMountedState;
  const useMountedWhen: typeof import("./composables/useLifecycle").useMountedWhen;
  const useMouse: typeof import("./composables/useMouse").useMouse;
  const useMouseInElement: typeof import("./composables/useMouse").useMouseInElement;
  const useMousePressed: typeof import("./composables/useMouse").useMousePressed;
  const useNetwork: typeof import("./composables/useNetwork").useNetwork;
  const useNetworkBanner: typeof import("./composables/useNetwork").useNetworkBanner;
  const useNetworkSpeed: typeof import("./composables/useNetwork").useNetworkSpeed;
  const useNotificationPermission: typeof import("./composables/usePermission").useNotificationPermission;
  const useNotificationQueue: typeof import("./composables/useQueue").useNotificationQueue;
  const useNow: typeof import("./composables/useTimer").useNow;
  const useNumberTransition: typeof import("./composables/useTransition").useNumberTransition;
  const useObject: typeof import("./composables/useRef").useObject;
  const useOnline: typeof import("./composables/useNetwork").useOnline;
  const useOptionalInject: typeof import("./composables/useProvide").useOptionalInject;
  const usePageLeave: typeof import("./composables/useTitle").usePageLeave;
  const usePaginatedFetch: typeof import("./composables/useFetch").usePaginatedFetch;
  const useParentComponent: typeof import("./composables/useComponent").useParentComponent;
  const usePermission: typeof import("./composables/usePermission").usePermission;
  const usePictureInPicture: typeof import("./composables/useMedia").usePictureInPicture;
  const usePolling: typeof import("./composables/useAsync").usePolling;
  const usePreferredColorScheme: typeof import("./composables/usePreferences").usePreferredColorScheme;
  const usePreferredContrast: typeof import("./composables/usePreferences").usePreferredContrast;
  const usePreferredDark: typeof import("./composables/usePreferences").usePreferredDark;
  const usePreferredLanguage: typeof import("./composables/usePreferences").usePreferredLanguage;
  const usePreferredReducedMotion: typeof import("./composables/usePreferences").usePreferredReducedMotion;
  const usePreferredTransparency: typeof import("./composables/usePreferences").usePreferredTransparency;
  const usePrefersContrast: typeof import("./composables/useWindowSize").usePrefersContrast;
  const usePrefersDark: typeof import("./composables/useWindowSize").usePrefersDark;
  const usePrefersReducedMotion: typeof import("./composables/useWindowSize").usePrefersReducedMotion;
  const usePrevious: typeof import("./composables/useRef").usePrevious;
  const useProgressiveImage: typeof import("./composables/useImage").useProgressiveImage;
  const usePromiseQueue: typeof import("./composables/useAsync").usePromiseQueue;
  const useProxyModel: typeof import("./composables/useVModel").useProxyModel;
  const usePulse: typeof import("./composables/useTransition").usePulse;
  const useQueue: typeof import("./composables/useQueue").useQueue;
  const useRafFn: typeof import("./composables/useTimer").useRafFn;
  const useRecorder: typeof import("./composables/useMedia").useRecorder;
  const useRenderCount: typeof import("./composables/useLifecycle").useRenderCount;
  const useRenderTracking: typeof import("./composables/useLifecycle").useRenderTracking;
  const useRequiredInject: typeof import("./composables/useProvide").useRequiredInject;
  const useRingBuffer: typeof import("./composables/useQueue").useRingBuffer;
  const useRootComponent: typeof import("./composables/useComponent").useRootComponent;
  const useRoute: typeof import("vue-router").useRoute;
  const useRouter: typeof import("vue-router").useRouter;
  const useSWR: typeof import("./composables/useSWR").useSWR;
  const useSWRInfinite: typeof import("./composables/useSWR").useSWRInfinite;
  const useSWRMutation: typeof import("./composables/useSWR").useSWRMutation;
  const useSafeMounted: typeof import("./composables/useLifecycle").useSafeMounted;
  const useScale: typeof import("./composables/useTransition").useScale;
  const useScheduler: typeof import("./composables/useTimer").useScheduler;
  const useScreenShare: typeof import("./composables/useMedia").useScreenShare;
  const useScreenWakeLock: typeof import("./composables/usePermission").useScreenWakeLock;
  const useScript: typeof import("./composables/useTitle").useScript;
  const useScrollDirection: typeof import("./composables/useScrollLock").useScrollDirection;
  const useScrollLock: typeof import("./composables/useScrollLock").useScrollLock;
  const useScrollLockWhenTrue: typeof import("./composables/useScrollLock").useScrollLockWhenTrue;
  const useScrollPosition: typeof import("./composables/useScrollLock").useScrollPosition;
  const useSearchDebounce: typeof import("./composables/useDebounce").useSearchDebounce;
  const useServerSentEvents: typeof import("./composables/useEventSource").useServerSentEvents;
  const useSessionStorage: typeof import("./composables/useStorage").useSessionStorage;
  const useSet: typeof import("./composables/useRef").useSet;
  const useShake: typeof import("./composables/useTransition").useShake;
  const useShortcut: typeof import("./composables/useKeyboard").useShortcut;
  const useSlide: typeof import("./composables/useTransition").useSlide;
  const useSlotPass: typeof import("./composables/useComponent").useSlotPass;
  const useSlots: typeof import("vue").useSlots;
  const useSlotsInfo: typeof import("./composables/useComponent").useSlotsInfo;
  const useSnapshot: typeof import("./composables/useHistory").useSnapshot;
  const useSortable: typeof import("./composables/useDraggable").useSortable;
  const useStack: typeof import("./composables/useQueue").useStack;
  const useStopwatch: typeof import("./composables/useCountdown").useStopwatch;
  const useStorage: typeof import("./composables/useStorage").useStorage;
  const useStyleMerge: typeof import("./composables/useComponent").useStyleMerge;
  const useStylesheet: typeof import("./composables/useTitle").useStylesheet;
  const useSyncedRef: typeof import("./composables/useClone").useSyncedRef;
  const useTabLeader: typeof import("./composables/useBroadcastChannel").useTabLeader;
  const useTabMessenger: typeof import("./composables/useBroadcastChannel").useTabMessenger;
  const useTabSync: typeof import("./composables/useBroadcastChannel").useTabSync;
  const useTargetDateCountdown: typeof import("./composables/useCountdown").useTargetDateCountdown;
  const useTaskQueue: typeof import("./composables/useQueue").useTaskQueue;
  const useTemplateRef: typeof import("vue").useTemplateRef;
  const useThrottledVModel: typeof import("./composables/useVModel").useThrottledVModel;
  const useTimeout: typeof import("./composables/useTimer").useTimeout;
  const useTimeoutFn: typeof import("./composables/useTimer").useTimeoutFn;
  const useTimestamp: typeof import("./composables/useTimer").useTimestamp;
  const useTimestampedHistory: typeof import("./composables/useHistory").useTimestampedHistory;
  const useTitle: typeof import("./composables/useTitle").useTitle;
  const useTitleTemplate: typeof import("./composables/useTitle").useTitleTemplate;
  const useToggle: typeof import("./composables/useVModel").useToggle;
  const useTransition: typeof import("./composables/useTransition").useTransition;
  const useTransitionGroup: typeof import("./composables/useTransition").useTransitionGroup;
  const useTypewriter: typeof import("./composables/useTransition").useTypewriter;
  const useUnmounted: typeof import("./composables/useLifecycle").useUnmounted;
  const useUpdated: typeof import("./composables/useLifecycle").useUpdated;
  const useVModel: typeof import("./composables/useVModel").useVModel;
  const useVModels: typeof import("./composables/useVModel").useVModels;
  const useVerificationCode: typeof import("./composables/useCountdown").useVerificationCode;
  const useVisibility: typeof import("./composables/useIntersectionObserver").useVisibility;
  const useWatchArray: typeof import("./composables/useWatch").useWatchArray;
  const useWebSocket: typeof import("./composables/useWebSocket").useWebSocket;
  const useWebSocketBinary: typeof import("./composables/useWebSocket").useWebSocketBinary;
  const useWebSocketJSON: typeof import("./composables/useWebSocket").useWebSocketJSON;
  const useWindowSize: typeof import("./composables/useWindowSize").useWindowSize;
  const vClickOutside: typeof import("./composables/useClickOutside").vClickOutside;
  const validateImage: typeof import("./composables/useImage").validateImage;
  const watch: typeof import("vue").watch;
  const watchArray: typeof import("./composables/useWatch").watchArray;
  const watchAtMost: typeof import("./composables/useWatch").watchAtMost;
  const watchDebounced: typeof import("./composables/useWatch").watchDebounced;
  const watchEffect: typeof import("vue").watchEffect;
  const watchIgnorable: typeof import("./composables/useWatch").watchIgnorable;
  const watchOnce: typeof import("./composables/useWatch").watchOnce;
  const watchPausable: typeof import("./composables/useWatch").watchPausable;
  const watchPostEffect: typeof import("vue").watchPostEffect;
  const watchReactive: typeof import("./composables/useReactive").watchReactive;
  const watchSyncEffect: typeof import("vue").watchSyncEffect;
  const watchThrottled: typeof import("./composables/useWatch").watchThrottled;
  const watchTriggered: typeof import("./composables/useWatch").watchTriggered;
  const watchWithFilter: typeof import("./composables/useWatch").watchWithFilter;
  const whenever: typeof import("./composables/useWatch").whenever;
  const writableComputed: typeof import("./composables/useComputed").writableComputed;
}
// for type re-export
declare global {
  // @ts-ignore
  export type {
    Component,
    Slot,
    Slots,
    ComponentPublicInstance,
    ComputedRef,
    DirectiveBinding,
    ExtractDefaultPropTypes,
    ExtractPropTypes,
    ExtractPublicPropTypes,
    InjectionKey,
    PropType,
    Ref,
    ShallowRef,
    MaybeRef,
    MaybeRefOrGetter,
    VNode,
    WritableComputedRef,
  } from "vue";
  import("vue");
  // @ts-ignore
  export type {
    UseAsyncStateOptions,
    UseAsyncStateReturn,
    UseAsyncRetryOptions,
    UsePollingOptions,
  } from "./composables/useAsync";
  import("./composables/useAsync");
  // @ts-ignore
  export type {
    UseBroadcastChannelOptions,
    UseBroadcastChannelReturn,
    UseBroadcastChannelJSONOptions,
    UseTabSyncOptions,
    UseTabSyncReturn,
    UseTabLeaderOptions,
    UseTabLeaderReturn,
    MessageHandler,
    UseTabMessengerReturn,
  } from "./composables/useBroadcastChannel";
  import("./composables/useBroadcastChannel");
  // @ts-ignore
  export type {
    UseClickOutsideOptions,
    UseClickOutsideToggleOptions,
    ClickOutsideBinding,
  } from "./composables/useClickOutside";
  import("./composables/useClickOutside");
  // @ts-ignore
  export type { UseClipboardOptions } from "./composables/useClipboard";
  import("./composables/useClipboard");
  // @ts-ignore
  export type {
    UseClonedOptions,
    UseClonedReturn,
    UseManualCloneReturn,
    UseDirtyStateReturn,
    UseSnapshotReturn,
    UseSyncedRefOptions,
    UseSyncedRefReturn,
    UseMemoizeReturn,
  } from "./composables/useClone";
  import("./composables/useClone");
  // @ts-ignore
  export type { SlotInfo, ComponentInfo, ComponentRefReturn, ExposeOptions } from "./composables/useComponent";
  import("./composables/useComponent");
  // @ts-ignore
  export type {
    ComputedAsyncOptions,
    ComputedAsyncReturn,
    ComputedWithControlOptions,
    ComputedWithControlReturn,
    ComputedDebouncedOptions,
    ComputedThrottledOptions,
  } from "./composables/useComputed";
  import("./composables/useComputed");
  // @ts-ignore
  export type { ConfirmOptions } from "./composables/useConfirm";
  import("./composables/useConfirm");
  // @ts-ignore
  export type {
    UseCountdownOptions,
    UseCountdownReturn,
    UseStopwatchOptions,
    UseVerificationCodeOptions,
    UseTargetDateCountdownOptions,
  } from "./composables/useCountdown";
  import("./composables/useCountdown");
  // @ts-ignore
  export type { UseDebounceOptions } from "./composables/useDebounce";
  import("./composables/useDebounce");
  // @ts-ignore
  export type {
    UseSortableOptions,
    UseDraggableReturn,
    DragItemProps,
    DragContainerProps,
    UseFileDropOptions,
  } from "./composables/useDraggable";
  import("./composables/useDraggable");
  // @ts-ignore
  export type { EventHandler, UnsubscribeFn, EventBus, GlobalEvents, AppEvents } from "./composables/useEventBus";
  import("./composables/useEventBus");
  // @ts-ignore
  export type {
    EventSourceStatus,
    UseEventSourceOptions,
    UseEventSourceReturn,
    UseEventSourceNamedOptions,
    NamedEventData,
    UseEventSourceNamedReturn,
    EventSourceManager,
  } from "./composables/useEventSource";
  import("./composables/useEventSource");
  // @ts-ignore
  export type {
    FetchStatus,
    UseFetchOptions,
    UseFetchReturn,
    CreateFetchOptions,
    CreateFetchReturn,
    UsePaginatedFetchOptions,
    UsePaginatedFetchReturn,
    UseInfiniteFetchOptions,
    UseInfiniteFetchReturn,
  } from "./composables/useFetch";
  import("./composables/useFetch");
  // @ts-ignore
  export type { UseFocusTrapOptions } from "./composables/useFocusTrap";
  import("./composables/useFocusTrap");
  // @ts-ignore
  export type { UseFormOptions, UseFormReturn, FieldProps, UseFormDirtyGuardOptions } from "./composables/useForm";
  import("./composables/useForm");
  // @ts-ignore
  export type { UseFullscreenOptions, UseFullscreenReturn } from "./composables/useFullscreen";
  import("./composables/useFullscreen");
  // @ts-ignore
  export type {
    GeolocationCoordinates,
    GeolocationPosition,
    UseGeolocationOptions,
    UseGeolocationReturn,
    DistanceUnit,
    UseGeolocationWatchOptions,
    GeolocationBounds,
    UseGeolocationBoundsOptions,
  } from "./composables/useGeolocation";
  import("./composables/useGeolocation");
  // @ts-ignore
  export type { UseHistoryOptions, UseHistoryReturn, HistoryEntry, UseSnapshotOptions } from "./composables/useHistory";
  import("./composables/useHistory");
  // @ts-ignore
  export type {
    UseImageOptions,
    UseImageReturn,
    UseImagePreloadReturn,
    UseLazyImageOptions,
    UseLazyImageReturn,
    UseProgressiveImageOptions,
    UseProgressiveImageReturn,
    ImageValidationResult,
    UseImageValidationOptions,
    UseImageCompressionOptions,
    UseImageCompressionReturn,
  } from "./composables/useImage";
  import("./composables/useImage");
  // @ts-ignore
  export type {
    UseIntersectionObserverOptions,
    UseIntersectionObserverReturn,
    UseLazyLoadOptions,
    UseInfiniteScrollOptions,
    UseAnimateOnScrollOptions,
    UseVisibilityOptions,
  } from "./composables/useIntersectionObserver";
  import("./composables/useIntersectionObserver");
  // @ts-ignore
  export type { KeyboardShortcut } from "./composables/useKeyboard";
  import("./composables/useKeyboard");
  // @ts-ignore
  export type {
    MountedState,
    LifecycleTrackerOptions,
    LifecycleEvent,
    LifecycleTrackerReturn,
    AsyncMountedOptions,
    CleanupFn,
  } from "./composables/useLifecycle";
  import("./composables/useLifecycle");
  // @ts-ignore
  export type {
    MediaState,
    UseMediaOptions,
    UseMediaReturn,
    AudioVisualizerOptions,
    AudioVisualizerReturn,
    RecorderOptions,
    UseRecorderReturn,
  } from "./composables/useMedia";
  import("./composables/useMedia");
  // @ts-ignore
  export type {
    MousePosition,
    UseMouseOptions,
    UseMouseReturn,
    UseMousePressedOptions,
    UseMousePressedReturn,
    UseMouseInElementOptions,
    UseMouseInElementReturn,
    UseHoverOptions,
    UseHoverReturn,
    CursorType,
    UseCursorReturn,
    UseDropZoneOptions,
    UseDropZoneReturn,
  } from "./composables/useMouse";
  import("./composables/useMouse");
  // @ts-ignore
  export type {
    NetworkState,
    UseNetworkOptions,
    UseOnlineOptions,
    UseNetworkSpeedOptions,
  } from "./composables/useNetwork";
  import("./composables/useNetwork");
  // @ts-ignore
  export type {
    PermissionName,
    PermissionState,
    UsePermissionOptions,
    UsePermissionReturn,
    UseNotificationPermissionReturn,
    UseClipboardPermissionReturn,
    UseCameraPermissionReturn,
    UseMicrophonePermissionReturn,
    UseGeolocationPermissionReturn,
    UseScreenWakeLockReturn,
  } from "./composables/usePermission";
  import("./composables/usePermission");
  // @ts-ignore
  export type {
    UsePreferredDarkReturn,
    UsePreferredLanguageReturn,
    UsePreferredReducedMotionReturn,
    UsePreferredContrastReturn,
    UsePreferredColorSchemeReturn,
    UseDarkOptions,
    UseDarkReturn,
    ColorMode,
    UseColorModeOptions,
    UseColorModeReturn,
    UsePreferredTransparencyReturn,
  } from "./composables/usePreferences";
  import("./composables/usePreferences");
  // @ts-ignore
  export type {
    CreateContextReturn,
    CreateStateContextReturn,
    CreateReactiveContextReturn,
    EventBusContext,
    ThemeContext,
    I18nContext,
  } from "./composables/useProvide";
  import("./composables/useProvide");
  // @ts-ignore
  export type {
    QueueItem,
    QueueConfig,
    UseQueueReturn,
    TaskQueueConfig,
    TaskStatus,
    Task,
    UseTaskQueueReturn,
    NotificationQueueConfig,
    Notification,
    UseNotificationQueueReturn,
  } from "./composables/useQueue";
  import("./composables/useQueue");
  // @ts-ignore
  export type {
    ReactiveWithOptionsConfig,
    ReactiveHistoryOptions,
    ReactiveHistoryReturn,
    ReactiveFormReturn,
    ReactivePick,
    ReactiveOmit,
  } from "./composables/useReactive";
  import("./composables/useReactive");
  // @ts-ignore
  export type {
    RefDebouncedOptions,
    RefThrottledOptions,
    RefHistoryOptions,
    RefHistoryReturn,
    RefAutoResetOptions,
    RefWithControlOptions,
    RefWithControlReturn,
    TemplateRefReturn,
  } from "./composables/useRef";
  import("./composables/useRef");
  // @ts-ignore
  export type {
    SWRStatus,
    UseSWROptions,
    UseSWRReturn,
    UseSWRMutationOptions,
    UseSWRMutationReturn,
    UseSWRInfiniteOptions,
    UseSWRInfiniteReturn,
  } from "./composables/useSWR";
  import("./composables/useSWR");
  // @ts-ignore
  export type { UseScrollLockOptions } from "./composables/useScrollLock";
  import("./composables/useScrollLock");
  // @ts-ignore
  export type { UseStorageOptions } from "./composables/useStorage";
  import("./composables/useStorage");
  // @ts-ignore
  export type {
    UseTimeoutOptions,
    UseTimeoutReturn,
    UseIntervalOptions,
    UseIntervalReturn,
    UseTimestampOptions,
    UseTimestampReturn,
    UseRafFnOptions,
    UseRafFnReturn,
    UseDateFormatOptions,
    UseIdleCallbackOptions,
    UseIdleCallbackReturn,
    ScheduledTask,
    UseSchedulerReturn,
  } from "./composables/useTimer";
  import("./composables/useTimer");
  // @ts-ignore
  export type {
    UseTitleOptions,
    UseTitleReturn,
    UseTitleTemplateOptions,
    UseTitleTemplateReturn,
    UseFaviconOptions,
    UseFaviconReturn,
    UsePageLeaveOptions,
    UsePageLeaveReturn,
    DocumentVisibilityState,
    UseDocumentVisibilityReturn,
    HeadConfig,
    UseScriptOptions,
    UseScriptReturn,
    UseStylesheetOptions,
    UseStylesheetReturn,
  } from "./composables/useTitle";
  import("./composables/useTitle");
  // @ts-ignore
  export type {
    TransitionState,
    EasingFunction,
    TransitionConfig,
    UseTransitionReturn,
    AnimationConfig,
    UseAnimationReturn,
    FadeConfig,
    SlideConfig,
  } from "./composables/useTransition";
  import("./composables/useTransition");
  // @ts-ignore
  export type {
    UseVModelOptions,
    UseProxyModelOptions,
    UseProxyModelReturn,
    UseControlledOptions,
    UseControlledReturn,
    UseDebouncedVModelOptions,
    UseThrottledVModelOptions,
    UseToggleOptions,
    UseToggleReturn,
    UseCycleListReturn,
  } from "./composables/useVModel";
  import("./composables/useVModel");
  // @ts-ignore
  export type {
    WatchOnceOptions,
    WatchDebouncedOptions,
    WatchThrottledOptions,
    WatchPausableReturn,
    WatchIgnorableReturn,
    WatchTriggeredReturn,
    WatchArrayReturn,
    WatchAtMostReturn,
    UntilReturn,
  } from "./composables/useWatch";
  import("./composables/useWatch");
  // @ts-ignore
  export type {
    WebSocketStatus,
    UseWebSocketOptions,
    UseWebSocketReturn,
    UseWebSocketJSONOptions,
    UseWebSocketJSONReturn,
    UseWebSocketBinaryOptions,
    UseWebSocketBinaryReturn,
    WebSocketManager,
  } from "./composables/useWebSocket";
  import("./composables/useWebSocket");
  // @ts-ignore
  export type {
    WindowSize,
    UseWindowSizeOptions,
    Breakpoint,
    UseMediaQueryOptions,
    UseElementSizeOptions,
  } from "./composables/useWindowSize";
  import("./composables/useWindowSize");
}

// for vue template auto import
import { UnwrapRef } from "vue";
declare module "vue" {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly BREAKPOINTS: UnwrapRef<(typeof import("./composables/useWindowSize"))["BREAKPOINTS"]>;
    readonly DISTANCE_UNITS: UnwrapRef<(typeof import("./composables/useGeolocation"))["DISTANCE_UNITS"]>;
    readonly EffectScope: UnwrapRef<(typeof import("vue"))["EffectScope"]>;
    readonly acceptHMRUpdate: UnwrapRef<(typeof import("pinia"))["acceptHMRUpdate"]>;
    readonly appEventBus: UnwrapRef<(typeof import("./composables/useEventBus"))["appEventBus"]>;
    readonly calculateDistance: UnwrapRef<(typeof import("./composables/useGeolocation"))["calculateDistance"]>;
    readonly clearFetchCache: UnwrapRef<(typeof import("./composables/useFetch"))["clearFetchCache"]>;
    readonly clearSWRCache: UnwrapRef<(typeof import("./composables/useSWR"))["clearSWRCache"]>;
    readonly clearStorageByPrefix: UnwrapRef<(typeof import("./composables/useStorage"))["clearStorageByPrefix"]>;
    readonly commonShortcuts: UnwrapRef<(typeof import("./composables/useKeyboard"))["commonShortcuts"]>;
    readonly computed: UnwrapRef<(typeof import("vue"))["computed"]>;
    readonly computedArray: UnwrapRef<(typeof import("./composables/useComputed"))["computedArray"]>;
    readonly computedAsync: UnwrapRef<(typeof import("./composables/useComputed"))["computedAsync"]>;
    readonly computedDebounced: UnwrapRef<(typeof import("./composables/useComputed"))["computedDebounced"]>;
    readonly computedDefault: UnwrapRef<(typeof import("./composables/useComputed"))["computedDefault"]>;
    readonly computedDelayed: UnwrapRef<(typeof import("./composables/useComputed"))["computedDelayed"]>;
    readonly computedEager: UnwrapRef<(typeof import("./composables/useComputed"))["computedEager"]>;
    readonly computedFilter: UnwrapRef<(typeof import("./composables/useComputed"))["computedFilter"]>;
    readonly computedFind: UnwrapRef<(typeof import("./composables/useComputed"))["computedFind"]>;
    readonly computedFrom: UnwrapRef<(typeof import("./composables/useComputed"))["computedFrom"]>;
    readonly computedGroupBy: UnwrapRef<(typeof import("./composables/useComputed"))["computedGroupBy"]>;
    readonly computedIf: UnwrapRef<(typeof import("./composables/useComputed"))["computedIf"]>;
    readonly computedMap: UnwrapRef<(typeof import("./composables/useComputed"))["computedMap"]>;
    readonly computedObject: UnwrapRef<(typeof import("./composables/useComputed"))["computedObject"]>;
    readonly computedOmit: UnwrapRef<(typeof import("./composables/useComputed"))["computedOmit"]>;
    readonly computedPick: UnwrapRef<(typeof import("./composables/useComputed"))["computedPick"]>;
    readonly computedSort: UnwrapRef<(typeof import("./composables/useComputed"))["computedSort"]>;
    readonly computedThrottled: UnwrapRef<(typeof import("./composables/useComputed"))["computedThrottled"]>;
    readonly computedWithControl: UnwrapRef<(typeof import("./composables/useComputed"))["computedWithControl"]>;
    readonly computedWithHistory: UnwrapRef<(typeof import("./composables/useComputed"))["computedWithHistory"]>;
    readonly createApp: UnwrapRef<(typeof import("vue"))["createApp"]>;
    readonly createContext: UnwrapRef<(typeof import("./composables/useProvide"))["createContext"]>;
    readonly createEventBus: UnwrapRef<(typeof import("./composables/useEventBus"))["createEventBus"]>;
    readonly createEventBusContext: UnwrapRef<(typeof import("./composables/useProvide"))["createEventBusContext"]>;
    readonly createEventSourceManager: UnwrapRef<
      (typeof import("./composables/useEventSource"))["createEventSourceManager"]
    >;
    readonly createFactoryContext: UnwrapRef<(typeof import("./composables/useProvide"))["createFactoryContext"]>;
    readonly createFetch: UnwrapRef<(typeof import("./composables/useFetch"))["createFetch"]>;
    readonly createI18nContext: UnwrapRef<(typeof import("./composables/useProvide"))["createI18nContext"]>;
    readonly createPinia: UnwrapRef<(typeof import("pinia"))["createPinia"]>;
    readonly createReactiveContext: UnwrapRef<(typeof import("./composables/useProvide"))["createReactiveContext"]>;
    readonly createReadonlyContext: UnwrapRef<(typeof import("./composables/useProvide"))["createReadonlyContext"]>;
    readonly createStateContext: UnwrapRef<(typeof import("./composables/useProvide"))["createStateContext"]>;
    readonly createStorageContext: UnwrapRef<(typeof import("./composables/useProvide"))["createStorageContext"]>;
    readonly createThemeContext: UnwrapRef<(typeof import("./composables/useProvide"))["createThemeContext"]>;
    readonly createWebSocketManager: UnwrapRef<(typeof import("./composables/useWebSocket"))["createWebSocketManager"]>;
    readonly customRef: UnwrapRef<(typeof import("vue"))["customRef"]>;
    readonly decimalToDms: UnwrapRef<(typeof import("./composables/useGeolocation"))["decimalToDms"]>;
    readonly deepClone: UnwrapRef<(typeof import("./composables/useClone"))["deepClone"]>;
    readonly defineAsyncComponent: UnwrapRef<(typeof import("vue"))["defineAsyncComponent"]>;
    readonly defineComponent: UnwrapRef<(typeof import("vue"))["defineComponent"]>;
    readonly defineStore: UnwrapRef<(typeof import("pinia"))["defineStore"]>;
    readonly deleteFetchCache: UnwrapRef<(typeof import("./composables/useFetch"))["deleteFetchCache"]>;
    readonly deleteSWRCache: UnwrapRef<(typeof import("./composables/useSWR"))["deleteSWRCache"]>;
    readonly dmsToDecimal: UnwrapRef<(typeof import("./composables/useGeolocation"))["dmsToDecimal"]>;
    readonly effectScope: UnwrapRef<(typeof import("vue"))["effectScope"]>;
    readonly formatCoordinates: UnwrapRef<(typeof import("./composables/useGeolocation"))["formatCoordinates"]>;
    readonly formatDistance: UnwrapRef<(typeof import("./composables/useGeolocation"))["formatDistance"]>;
    readonly formatDuration: UnwrapRef<(typeof import("./composables/useMedia"))["formatDuration"]>;
    readonly getActivePinia: UnwrapRef<(typeof import("pinia"))["getActivePinia"]>;
    readonly getAppleMapsUrl: UnwrapRef<(typeof import("./composables/useGeolocation"))["getAppleMapsUrl"]>;
    readonly getCurrentInstance: UnwrapRef<(typeof import("vue"))["getCurrentInstance"]>;
    readonly getCurrentScope: UnwrapRef<(typeof import("vue"))["getCurrentScope"]>;
    readonly getCurrentWatcher: UnwrapRef<(typeof import("vue"))["getCurrentWatcher"]>;
    readonly getDragItemClasses: UnwrapRef<(typeof import("./composables/useDraggable"))["getDragItemClasses"]>;
    readonly getFetchCacheSize: UnwrapRef<(typeof import("./composables/useFetch"))["getFetchCacheSize"]>;
    readonly getGlobalEventBus: UnwrapRef<(typeof import("./composables/useEventBus"))["getGlobalEventBus"]>;
    readonly getGoogleMapsUrl: UnwrapRef<(typeof import("./composables/useGeolocation"))["getGoogleMapsUrl"]>;
    readonly getNavigationUrl: UnwrapRef<(typeof import("./composables/useGeolocation"))["getNavigationUrl"]>;
    readonly getSWRCache: UnwrapRef<(typeof import("./composables/useSWR"))["getSWRCache"]>;
    readonly h: UnwrapRef<(typeof import("vue"))["h"]>;
    readonly inject: UnwrapRef<(typeof import("vue"))["inject"]>;
    readonly isPermissionsApiSupported: UnwrapRef<
      (typeof import("./composables/usePermission"))["isPermissionsApiSupported"]
    >;
    readonly isProxy: UnwrapRef<(typeof import("vue"))["isProxy"]>;
    readonly isReactive: UnwrapRef<(typeof import("vue"))["isReactive"]>;
    readonly isReadonly: UnwrapRef<(typeof import("vue"))["isReadonly"]>;
    readonly isRef: UnwrapRef<(typeof import("vue"))["isRef"]>;
    readonly isShallow: UnwrapRef<(typeof import("vue"))["isShallow"]>;
    readonly mapActions: UnwrapRef<(typeof import("pinia"))["mapActions"]>;
    readonly mapGetters: UnwrapRef<(typeof import("pinia"))["mapGetters"]>;
    readonly mapState: UnwrapRef<(typeof import("pinia"))["mapState"]>;
    readonly mapStores: UnwrapRef<(typeof import("pinia"))["mapStores"]>;
    readonly mapWritableState: UnwrapRef<(typeof import("pinia"))["mapWritableState"]>;
    readonly markRaw: UnwrapRef<(typeof import("vue"))["markRaw"]>;
    readonly nextTick: UnwrapRef<(typeof import("vue"))["nextTick"]>;
    readonly onActivated: UnwrapRef<(typeof import("vue"))["onActivated"]>;
    readonly onBeforeMount: UnwrapRef<(typeof import("vue"))["onBeforeMount"]>;
    readonly onBeforeRouteLeave: UnwrapRef<(typeof import("vue-router"))["onBeforeRouteLeave"]>;
    readonly onBeforeRouteUpdate: UnwrapRef<(typeof import("vue-router"))["onBeforeRouteUpdate"]>;
    readonly onBeforeUnmount: UnwrapRef<(typeof import("vue"))["onBeforeUnmount"]>;
    readonly onBeforeUpdate: UnwrapRef<(typeof import("vue"))["onBeforeUpdate"]>;
    readonly onDeactivated: UnwrapRef<(typeof import("vue"))["onDeactivated"]>;
    readonly onErrorCaptured: UnwrapRef<(typeof import("vue"))["onErrorCaptured"]>;
    readonly onMounted: UnwrapRef<(typeof import("vue"))["onMounted"]>;
    readonly onRenderTracked: UnwrapRef<(typeof import("vue"))["onRenderTracked"]>;
    readonly onRenderTriggered: UnwrapRef<(typeof import("vue"))["onRenderTriggered"]>;
    readonly onScopeDispose: UnwrapRef<(typeof import("vue"))["onScopeDispose"]>;
    readonly onServerPrefetch: UnwrapRef<(typeof import("vue"))["onServerPrefetch"]>;
    readonly onUnmounted: UnwrapRef<(typeof import("vue"))["onUnmounted"]>;
    readonly onUpdated: UnwrapRef<(typeof import("vue"))["onUpdated"]>;
    readonly onWatcherCleanup: UnwrapRef<(typeof import("vue"))["onWatcherCleanup"]>;
    readonly provide: UnwrapRef<(typeof import("vue"))["provide"]>;
    readonly queryPermissions: UnwrapRef<(typeof import("./composables/usePermission"))["queryPermissions"]>;
    readonly reactive: UnwrapRef<(typeof import("vue"))["reactive"]>;
    readonly reactiveDefault: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveDefault"]>;
    readonly reactiveExtend: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveExtend"]>;
    readonly reactiveForm: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveForm"]>;
    readonly reactiveHistory: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveHistory"]>;
    readonly reactiveMerge: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveMerge"]>;
    readonly reactiveOmit: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveOmit"]>;
    readonly reactivePick: UnwrapRef<(typeof import("./composables/useReactive"))["reactivePick"]>;
    readonly reactiveResettable: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveResettable"]>;
    readonly reactiveTransform: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveTransform"]>;
    readonly reactiveUtils: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveUtils"]>;
    readonly reactiveValidated: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveValidated"]>;
    readonly reactiveWhen: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveWhen"]>;
    readonly reactiveWithOptions: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveWithOptions"]>;
    readonly reactiveWithReadonly: UnwrapRef<(typeof import("./composables/useReactive"))["reactiveWithReadonly"]>;
    readonly readonly: UnwrapRef<(typeof import("vue"))["readonly"]>;
    readonly ref: UnwrapRef<(typeof import("vue"))["ref"]>;
    readonly refAutoReset: UnwrapRef<(typeof import("./composables/useRef"))["refAutoReset"]>;
    readonly refDebounced: UnwrapRef<(typeof import("./composables/useRef"))["refDebounced"]>;
    readonly refDefault: UnwrapRef<(typeof import("./composables/useRef"))["refDefault"]>;
    readonly refHistory: UnwrapRef<(typeof import("./composables/useRef"))["refHistory"]>;
    readonly refLocked: UnwrapRef<(typeof import("./composables/useRef"))["refLocked"]>;
    readonly refThrottled: UnwrapRef<(typeof import("./composables/useRef"))["refThrottled"]>;
    readonly refWithControl: UnwrapRef<(typeof import("./composables/useRef"))["refWithControl"]>;
    readonly resolveComponent: UnwrapRef<(typeof import("vue"))["resolveComponent"]>;
    readonly revalidateSWR: UnwrapRef<(typeof import("./composables/useSWR"))["revalidateSWR"]>;
    readonly setActivePinia: UnwrapRef<(typeof import("pinia"))["setActivePinia"]>;
    readonly setMapStoreSuffix: UnwrapRef<(typeof import("pinia"))["setMapStoreSuffix"]>;
    readonly setSWRCache: UnwrapRef<(typeof import("./composables/useSWR"))["setSWRCache"]>;
    readonly shallowReactive: UnwrapRef<(typeof import("vue"))["shallowReactive"]>;
    readonly shallowReadonly: UnwrapRef<(typeof import("vue"))["shallowReadonly"]>;
    readonly shallowRef: UnwrapRef<(typeof import("vue"))["shallowRef"]>;
    readonly storeToRefs: UnwrapRef<(typeof import("pinia"))["storeToRefs"]>;
    readonly structuredClonePolyfill: UnwrapRef<(typeof import("./composables/useClone"))["structuredClonePolyfill"]>;
    readonly syncReactive: UnwrapRef<(typeof import("./composables/useReactive"))["syncReactive"]>;
    readonly syncRefs: UnwrapRef<(typeof import("./composables/useRef"))["syncRefs"]>;
    readonly templateRef: UnwrapRef<(typeof import("./composables/useRef"))["templateRef"]>;
    readonly toComputed: UnwrapRef<(typeof import("./composables/useComputed"))["toComputed"]>;
    readonly toRaw: UnwrapRef<(typeof import("vue"))["toRaw"]>;
    readonly toRef: UnwrapRef<(typeof import("vue"))["toRef"]>;
    readonly toRefs: UnwrapRef<(typeof import("vue"))["toRefs"]>;
    readonly toValue: UnwrapRef<(typeof import("vue"))["toValue"]>;
    readonly triggerRef: UnwrapRef<(typeof import("vue"))["triggerRef"]>;
    readonly unref: UnwrapRef<(typeof import("vue"))["unref"]>;
    readonly until: UnwrapRef<(typeof import("./composables/useWatch"))["until"]>;
    readonly useActivated: UnwrapRef<(typeof import("./composables/useLifecycle"))["useActivated"]>;
    readonly useAnimateOnScroll: UnwrapRef<
      (typeof import("./composables/useIntersectionObserver"))["useAnimateOnScroll"]
    >;
    readonly useAnimation: UnwrapRef<(typeof import("./composables/useTransition"))["useAnimation"]>;
    readonly useAppEventBus: UnwrapRef<(typeof import("./composables/useEventBus"))["useAppEventBus"]>;
    readonly useArray: UnwrapRef<(typeof import("./composables/useRef"))["useArray"]>;
    readonly useAsyncMounted: UnwrapRef<(typeof import("./composables/useLifecycle"))["useAsyncMounted"]>;
    readonly useAsyncRef: UnwrapRef<(typeof import("./composables/useAsync"))["useAsyncRef"]>;
    readonly useAsyncRetry: UnwrapRef<(typeof import("./composables/useAsync"))["useAsyncRetry"]>;
    readonly useAsyncState: UnwrapRef<(typeof import("./composables/useAsync"))["useAsyncState"]>;
    readonly useAttrs: UnwrapRef<(typeof import("vue"))["useAttrs"]>;
    readonly useAttrsEnhanced: UnwrapRef<(typeof import("./composables/useComponent"))["useAttrsEnhanced"]>;
    readonly useAudio: UnwrapRef<(typeof import("./composables/useMedia"))["useAudio"]>;
    readonly useAudioVisualizer: UnwrapRef<(typeof import("./composables/useMedia"))["useAudioVisualizer"]>;
    readonly useAuthStore: UnwrapRef<(typeof import("@/stores/auth"))["useAuthStore"]>;
    readonly useAutoFocus: UnwrapRef<(typeof import("./composables/useFocusTrap"))["useAutoFocus"]>;
    readonly useBoolean: UnwrapRef<(typeof import("./composables/useRef"))["useBoolean"]>;
    readonly useBroadcastChannel: UnwrapRef<
      (typeof import("./composables/useBroadcastChannel"))["useBroadcastChannel"]
    >;
    readonly useBroadcastChannelJSON: UnwrapRef<
      (typeof import("./composables/useBroadcastChannel"))["useBroadcastChannelJSON"]
    >;
    readonly useCameraPermission: UnwrapRef<(typeof import("./composables/usePermission"))["useCameraPermission"]>;
    readonly useCanHover: UnwrapRef<(typeof import("./composables/useWindowSize"))["useCanHover"]>;
    readonly useClassMerge: UnwrapRef<(typeof import("./composables/useComponent"))["useClassMerge"]>;
    readonly useCleanup: UnwrapRef<(typeof import("./composables/useLifecycle"))["useCleanup"]>;
    readonly useClickOutside: UnwrapRef<(typeof import("./composables/useClickOutside"))["useClickOutside"]>;
    readonly useClickOutsideToggle: UnwrapRef<
      (typeof import("./composables/useClickOutside"))["useClickOutsideToggle"]
    >;
    readonly useClipboard: UnwrapRef<(typeof import("./composables/useClipboard"))["useClipboard"]>;
    readonly useClipboardPermission: UnwrapRef<
      (typeof import("./composables/usePermission"))["useClipboardPermission"]
    >;
    readonly useCloned: UnwrapRef<(typeof import("./composables/useClone"))["useCloned"]>;
    readonly useColorMode: UnwrapRef<(typeof import("./composables/usePreferences"))["useColorMode"]>;
    readonly useComponentAliveTime: UnwrapRef<(typeof import("./composables/useLifecycle"))["useComponentAliveTime"]>;
    readonly useComponentEmit: UnwrapRef<(typeof import("./composables/useComponent"))["useComponentEmit"]>;
    readonly useComponentInfo: UnwrapRef<(typeof import("./composables/useComponent"))["useComponentInfo"]>;
    readonly useComponentProxy: UnwrapRef<(typeof import("./composables/useComponent"))["useComponentProxy"]>;
    readonly useComponentRef: UnwrapRef<(typeof import("./composables/useComponent"))["useComponentRef"]>;
    readonly useComponentRefs: UnwrapRef<(typeof import("./composables/useComponent"))["useComponentRefs"]>;
    readonly useComponentType: UnwrapRef<(typeof import("./composables/useComponent"))["useComponentType"]>;
    readonly useComponentVisible: UnwrapRef<(typeof import("./composables/useLifecycle"))["useComponentVisible"]>;
    readonly useConditionalSlot: UnwrapRef<(typeof import("./composables/useComponent"))["useConditionalSlot"]>;
    readonly useConfirm: UnwrapRef<(typeof import("./composables/useConfirm"))["useConfirm"]>;
    readonly useControlled: UnwrapRef<(typeof import("./composables/useVModel"))["useControlled"]>;
    readonly useCountdown: UnwrapRef<(typeof import("./composables/useCountdown"))["useCountdown"]>;
    readonly useCounter: UnwrapRef<(typeof import("./composables/useRef"))["useCounter"]>;
    readonly useCssModule: UnwrapRef<(typeof import("vue"))["useCssModule"]>;
    readonly useCssVars: UnwrapRef<(typeof import("vue"))["useCssVars"]>;
    readonly useCursor: UnwrapRef<(typeof import("./composables/useMouse"))["useCursor"]>;
    readonly useCustomProperties: UnwrapRef<(typeof import("./composables/useComponent"))["useCustomProperties"]>;
    readonly useCycleList: UnwrapRef<(typeof import("./composables/useVModel"))["useCycleList"]>;
    readonly useDark: UnwrapRef<(typeof import("./composables/usePreferences"))["useDark"]>;
    readonly useDateFormat: UnwrapRef<(typeof import("./composables/useTimer"))["useDateFormat"]>;
    readonly useDeactivated: UnwrapRef<(typeof import("./composables/useLifecycle"))["useDeactivated"]>;
    readonly useDebounceFn: UnwrapRef<(typeof import("./composables/useDebounce"))["useDebounceFn"]>;
    readonly useDebouncedRef: UnwrapRef<(typeof import("./composables/useDebounce"))["useDebouncedRef"]>;
    readonly useDebouncedVModel: UnwrapRef<(typeof import("./composables/useVModel"))["useDebouncedVModel"]>;
    readonly useDirtyState: UnwrapRef<(typeof import("./composables/useClone"))["useDirtyState"]>;
    readonly useDocumentFullscreen: UnwrapRef<(typeof import("./composables/useFullscreen"))["useDocumentFullscreen"]>;
    readonly useDocumentTitle: UnwrapRef<(typeof import("./composables/useTitle"))["useDocumentTitle"]>;
    readonly useDocumentVisibility: UnwrapRef<(typeof import("./composables/useTitle"))["useDocumentVisibility"]>;
    readonly useDropZone: UnwrapRef<(typeof import("./composables/useMouse"))["useDropZone"]>;
    readonly useElementScrollLock: UnwrapRef<(typeof import("./composables/useScrollLock"))["useElementScrollLock"]>;
    readonly useElementSize: UnwrapRef<(typeof import("./composables/useWindowSize"))["useElementSize"]>;
    readonly useErrorCapture: UnwrapRef<(typeof import("./composables/useLifecycle"))["useErrorCapture"]>;
    readonly useEventBus: UnwrapRef<(typeof import("./composables/useEventBus"))["useEventBus"]>;
    readonly useEventListener: UnwrapRef<(typeof import("./composables/useEventBus"))["useEventListener"]>;
    readonly useEventSource: UnwrapRef<(typeof import("./composables/useEventSource"))["useEventSource"]>;
    readonly useEventSourceNamed: UnwrapRef<(typeof import("./composables/useEventSource"))["useEventSourceNamed"]>;
    readonly useEventValue: UnwrapRef<(typeof import("./composables/useEventBus"))["useEventValue"]>;
    readonly useExposeMethod: UnwrapRef<(typeof import("./composables/useComponent"))["useExposeMethod"]>;
    readonly useExposeState: UnwrapRef<(typeof import("./composables/useComponent"))["useExposeState"]>;
    readonly useFade: UnwrapRef<(typeof import("./composables/useTransition"))["useFade"]>;
    readonly useFavicon: UnwrapRef<(typeof import("./composables/useTitle"))["useFavicon"]>;
    readonly useFetch: UnwrapRef<(typeof import("./composables/useFetch"))["useFetch"]>;
    readonly useFieldArray: UnwrapRef<(typeof import("./composables/useForm"))["useFieldArray"]>;
    readonly useFileDrop: UnwrapRef<(typeof import("./composables/useDraggable"))["useFileDrop"]>;
    readonly useFocusReturn: UnwrapRef<(typeof import("./composables/useFocusTrap"))["useFocusReturn"]>;
    readonly useFocusTrap: UnwrapRef<(typeof import("./composables/useFocusTrap"))["useFocusTrap"]>;
    readonly useFocusTrapWhenTrue: UnwrapRef<(typeof import("./composables/useFocusTrap"))["useFocusTrapWhenTrue"]>;
    readonly useForceUpdate: UnwrapRef<(typeof import("./composables/useComponent"))["useForceUpdate"]>;
    readonly useForm: UnwrapRef<(typeof import("./composables/useForm"))["useForm"]>;
    readonly useFormDirtyGuard: UnwrapRef<(typeof import("./composables/useForm"))["useFormDirtyGuard"]>;
    readonly useFullscreen: UnwrapRef<(typeof import("./composables/useFullscreen"))["useFullscreen"]>;
    readonly useFullscreenButton: UnwrapRef<(typeof import("./composables/useFullscreen"))["useFullscreenButton"]>;
    readonly useGeolocation: UnwrapRef<(typeof import("./composables/useGeolocation"))["useGeolocation"]>;
    readonly useGeolocationBounds: UnwrapRef<(typeof import("./composables/useGeolocation"))["useGeolocationBounds"]>;
    readonly useGeolocationPermission: UnwrapRef<
      (typeof import("./composables/usePermission"))["useGeolocationPermission"]
    >;
    readonly useGeolocationWatch: UnwrapRef<(typeof import("./composables/useGeolocation"))["useGeolocationWatch"]>;
    readonly useHead: UnwrapRef<(typeof import("./composables/useTitle"))["useHead"]>;
    readonly useHistory: UnwrapRef<(typeof import("./composables/useHistory"))["useHistory"]>;
    readonly useHistoryQueue: UnwrapRef<(typeof import("./composables/useQueue"))["useHistoryQueue"]>;
    readonly useHover: UnwrapRef<(typeof import("./composables/useMouse"))["useHover"]>;
    readonly useId: UnwrapRef<(typeof import("vue"))["useId"]>;
    readonly useIdleCallback: UnwrapRef<(typeof import("./composables/useTimer"))["useIdleCallback"]>;
    readonly useImage: UnwrapRef<(typeof import("./composables/useImage"))["useImage"]>;
    readonly useImageCompression: UnwrapRef<(typeof import("./composables/useImage"))["useImageCompression"]>;
    readonly useImagePreload: UnwrapRef<(typeof import("./composables/useImage"))["useImagePreload"]>;
    readonly useInfiniteFetch: UnwrapRef<(typeof import("./composables/useFetch"))["useInfiniteFetch"]>;
    readonly useInfiniteScroll: UnwrapRef<
      (typeof import("./composables/useIntersectionObserver"))["useInfiniteScroll"]
    >;
    readonly useInstance: UnwrapRef<(typeof import("./composables/useLifecycle"))["useInstance"]>;
    readonly useIntersectionObserver: UnwrapRef<
      (typeof import("./composables/useIntersectionObserver"))["useIntersectionObserver"]
    >;
    readonly useInterval: UnwrapRef<(typeof import("./composables/useTimer"))["useInterval"]>;
    readonly useIntervalFn: UnwrapRef<(typeof import("./composables/useTimer"))["useIntervalFn"]>;
    readonly useIsRetina: UnwrapRef<(typeof import("./composables/useWindowSize"))["useIsRetina"]>;
    readonly useIsTouchDevice: UnwrapRef<(typeof import("./composables/useWindowSize"))["useIsTouchDevice"]>;
    readonly useKeyboard: UnwrapRef<(typeof import("./composables/useKeyboard"))["useKeyboard"]>;
    readonly useLatest: UnwrapRef<(typeof import("./composables/useRef"))["useLatest"]>;
    readonly useLazyFetch: UnwrapRef<(typeof import("./composables/useFetch"))["useLazyFetch"]>;
    readonly useLazyImage: UnwrapRef<(typeof import("./composables/useImage"))["useLazyImage"]>;
    readonly useLazyLoad: UnwrapRef<(typeof import("./composables/useIntersectionObserver"))["useLazyLoad"]>;
    readonly useLifecycle: UnwrapRef<(typeof import("./composables/useLifecycle"))["useLifecycle"]>;
    readonly useLifecycleTracker: UnwrapRef<(typeof import("./composables/useLifecycle"))["useLifecycleTracker"]>;
    readonly useLink: UnwrapRef<(typeof import("vue-router"))["useLink"]>;
    readonly useLocalStorage: UnwrapRef<(typeof import("./composables/useStorage"))["useLocalStorage"]>;
    readonly useManualClone: UnwrapRef<(typeof import("./composables/useClone"))["useManualClone"]>;
    readonly useManualHistory: UnwrapRef<(typeof import("./composables/useHistory"))["useManualHistory"]>;
    readonly useMap: UnwrapRef<(typeof import("./composables/useRef"))["useMap"]>;
    readonly useMedia: UnwrapRef<(typeof import("./composables/useMedia"))["useMedia"]>;
    readonly useMediaQuery: UnwrapRef<(typeof import("./composables/useWindowSize"))["useMediaQuery"]>;
    readonly useMemoize: UnwrapRef<(typeof import("./composables/useClone"))["useMemoize"]>;
    readonly useMicrophonePermission: UnwrapRef<
      (typeof import("./composables/usePermission"))["useMicrophonePermission"]
    >;
    readonly useModel: UnwrapRef<(typeof import("vue"))["useModel"]>;
    readonly useModelValue: UnwrapRef<(typeof import("./composables/useVModel"))["useModelValue"]>;
    readonly useMounted: UnwrapRef<(typeof import("./composables/useLifecycle"))["useMounted"]>;
    readonly useMountedDelay: UnwrapRef<(typeof import("./composables/useLifecycle"))["useMountedDelay"]>;
    readonly useMountedNextFrame: UnwrapRef<(typeof import("./composables/useLifecycle"))["useMountedNextFrame"]>;
    readonly useMountedNextTick: UnwrapRef<(typeof import("./composables/useLifecycle"))["useMountedNextTick"]>;
    readonly useMountedOnce: UnwrapRef<(typeof import("./composables/useLifecycle"))["useMountedOnce"]>;
    readonly useMountedOrActivated: UnwrapRef<(typeof import("./composables/useLifecycle"))["useMountedOrActivated"]>;
    readonly useMountedState: UnwrapRef<(typeof import("./composables/useLifecycle"))["useMountedState"]>;
    readonly useMountedWhen: UnwrapRef<(typeof import("./composables/useLifecycle"))["useMountedWhen"]>;
    readonly useMouse: UnwrapRef<(typeof import("./composables/useMouse"))["useMouse"]>;
    readonly useMouseInElement: UnwrapRef<(typeof import("./composables/useMouse"))["useMouseInElement"]>;
    readonly useMousePressed: UnwrapRef<(typeof import("./composables/useMouse"))["useMousePressed"]>;
    readonly useNetwork: UnwrapRef<(typeof import("./composables/useNetwork"))["useNetwork"]>;
    readonly useNetworkBanner: UnwrapRef<(typeof import("./composables/useNetwork"))["useNetworkBanner"]>;
    readonly useNetworkSpeed: UnwrapRef<(typeof import("./composables/useNetwork"))["useNetworkSpeed"]>;
    readonly useNotificationPermission: UnwrapRef<
      (typeof import("./composables/usePermission"))["useNotificationPermission"]
    >;
    readonly useNotificationQueue: UnwrapRef<(typeof import("./composables/useQueue"))["useNotificationQueue"]>;
    readonly useNow: UnwrapRef<(typeof import("./composables/useTimer"))["useNow"]>;
    readonly useNumberTransition: UnwrapRef<(typeof import("./composables/useTransition"))["useNumberTransition"]>;
    readonly useObject: UnwrapRef<(typeof import("./composables/useRef"))["useObject"]>;
    readonly useOnline: UnwrapRef<(typeof import("./composables/useNetwork"))["useOnline"]>;
    readonly useOptionalInject: UnwrapRef<(typeof import("./composables/useProvide"))["useOptionalInject"]>;
    readonly usePageLeave: UnwrapRef<(typeof import("./composables/useTitle"))["usePageLeave"]>;
    readonly usePaginatedFetch: UnwrapRef<(typeof import("./composables/useFetch"))["usePaginatedFetch"]>;
    readonly useParentComponent: UnwrapRef<(typeof import("./composables/useComponent"))["useParentComponent"]>;
    readonly usePermission: UnwrapRef<(typeof import("./composables/usePermission"))["usePermission"]>;
    readonly usePictureInPicture: UnwrapRef<(typeof import("./composables/useMedia"))["usePictureInPicture"]>;
    readonly usePolling: UnwrapRef<(typeof import("./composables/useAsync"))["usePolling"]>;
    readonly usePreferredColorScheme: UnwrapRef<
      (typeof import("./composables/usePreferences"))["usePreferredColorScheme"]
    >;
    readonly usePreferredContrast: UnwrapRef<(typeof import("./composables/usePreferences"))["usePreferredContrast"]>;
    readonly usePreferredDark: UnwrapRef<(typeof import("./composables/usePreferences"))["usePreferredDark"]>;
    readonly usePreferredLanguage: UnwrapRef<(typeof import("./composables/usePreferences"))["usePreferredLanguage"]>;
    readonly usePreferredReducedMotion: UnwrapRef<
      (typeof import("./composables/usePreferences"))["usePreferredReducedMotion"]
    >;
    readonly usePreferredTransparency: UnwrapRef<
      (typeof import("./composables/usePreferences"))["usePreferredTransparency"]
    >;
    readonly usePrefersContrast: UnwrapRef<(typeof import("./composables/useWindowSize"))["usePrefersContrast"]>;
    readonly usePrefersDark: UnwrapRef<(typeof import("./composables/useWindowSize"))["usePrefersDark"]>;
    readonly usePrefersReducedMotion: UnwrapRef<
      (typeof import("./composables/useWindowSize"))["usePrefersReducedMotion"]
    >;
    readonly usePrevious: UnwrapRef<(typeof import("./composables/useRef"))["usePrevious"]>;
    readonly useProgressiveImage: UnwrapRef<(typeof import("./composables/useImage"))["useProgressiveImage"]>;
    readonly usePromiseQueue: UnwrapRef<(typeof import("./composables/useAsync"))["usePromiseQueue"]>;
    readonly useProxyModel: UnwrapRef<(typeof import("./composables/useVModel"))["useProxyModel"]>;
    readonly usePulse: UnwrapRef<(typeof import("./composables/useTransition"))["usePulse"]>;
    readonly useQueue: UnwrapRef<(typeof import("./composables/useQueue"))["useQueue"]>;
    readonly useRafFn: UnwrapRef<(typeof import("./composables/useTimer"))["useRafFn"]>;
    readonly useRecorder: UnwrapRef<(typeof import("./composables/useMedia"))["useRecorder"]>;
    readonly useRenderCount: UnwrapRef<(typeof import("./composables/useLifecycle"))["useRenderCount"]>;
    readonly useRenderTracking: UnwrapRef<(typeof import("./composables/useLifecycle"))["useRenderTracking"]>;
    readonly useRequiredInject: UnwrapRef<(typeof import("./composables/useProvide"))["useRequiredInject"]>;
    readonly useRingBuffer: UnwrapRef<(typeof import("./composables/useQueue"))["useRingBuffer"]>;
    readonly useRootComponent: UnwrapRef<(typeof import("./composables/useComponent"))["useRootComponent"]>;
    readonly useRoute: UnwrapRef<(typeof import("vue-router"))["useRoute"]>;
    readonly useRouter: UnwrapRef<(typeof import("vue-router"))["useRouter"]>;
    readonly useSWR: UnwrapRef<(typeof import("./composables/useSWR"))["useSWR"]>;
    readonly useSWRInfinite: UnwrapRef<(typeof import("./composables/useSWR"))["useSWRInfinite"]>;
    readonly useSWRMutation: UnwrapRef<(typeof import("./composables/useSWR"))["useSWRMutation"]>;
    readonly useSafeMounted: UnwrapRef<(typeof import("./composables/useLifecycle"))["useSafeMounted"]>;
    readonly useScale: UnwrapRef<(typeof import("./composables/useTransition"))["useScale"]>;
    readonly useScheduler: UnwrapRef<(typeof import("./composables/useTimer"))["useScheduler"]>;
    readonly useScreenShare: UnwrapRef<(typeof import("./composables/useMedia"))["useScreenShare"]>;
    readonly useScreenWakeLock: UnwrapRef<(typeof import("./composables/usePermission"))["useScreenWakeLock"]>;
    readonly useScript: UnwrapRef<(typeof import("./composables/useTitle"))["useScript"]>;
    readonly useScrollDirection: UnwrapRef<(typeof import("./composables/useScrollLock"))["useScrollDirection"]>;
    readonly useScrollLock: UnwrapRef<(typeof import("./composables/useScrollLock"))["useScrollLock"]>;
    readonly useScrollLockWhenTrue: UnwrapRef<(typeof import("./composables/useScrollLock"))["useScrollLockWhenTrue"]>;
    readonly useScrollPosition: UnwrapRef<(typeof import("./composables/useScrollLock"))["useScrollPosition"]>;
    readonly useSearchDebounce: UnwrapRef<(typeof import("./composables/useDebounce"))["useSearchDebounce"]>;
    readonly useServerSentEvents: UnwrapRef<(typeof import("./composables/useEventSource"))["useServerSentEvents"]>;
    readonly useSessionStorage: UnwrapRef<(typeof import("./composables/useStorage"))["useSessionStorage"]>;
    readonly useSet: UnwrapRef<(typeof import("./composables/useRef"))["useSet"]>;
    readonly useShake: UnwrapRef<(typeof import("./composables/useTransition"))["useShake"]>;
    readonly useShortcut: UnwrapRef<(typeof import("./composables/useKeyboard"))["useShortcut"]>;
    readonly useSlide: UnwrapRef<(typeof import("./composables/useTransition"))["useSlide"]>;
    readonly useSlotPass: UnwrapRef<(typeof import("./composables/useComponent"))["useSlotPass"]>;
    readonly useSlots: UnwrapRef<(typeof import("vue"))["useSlots"]>;
    readonly useSlotsInfo: UnwrapRef<(typeof import("./composables/useComponent"))["useSlotsInfo"]>;
    readonly useSnapshot: UnwrapRef<(typeof import("./composables/useHistory"))["useSnapshot"]>;
    readonly useSortable: UnwrapRef<(typeof import("./composables/useDraggable"))["useSortable"]>;
    readonly useStack: UnwrapRef<(typeof import("./composables/useQueue"))["useStack"]>;
    readonly useStopwatch: UnwrapRef<(typeof import("./composables/useCountdown"))["useStopwatch"]>;
    readonly useStorage: UnwrapRef<(typeof import("./composables/useStorage"))["useStorage"]>;
    readonly useStyleMerge: UnwrapRef<(typeof import("./composables/useComponent"))["useStyleMerge"]>;
    readonly useStylesheet: UnwrapRef<(typeof import("./composables/useTitle"))["useStylesheet"]>;
    readonly useSyncedRef: UnwrapRef<(typeof import("./composables/useClone"))["useSyncedRef"]>;
    readonly useTabLeader: UnwrapRef<(typeof import("./composables/useBroadcastChannel"))["useTabLeader"]>;
    readonly useTabMessenger: UnwrapRef<(typeof import("./composables/useBroadcastChannel"))["useTabMessenger"]>;
    readonly useTabSync: UnwrapRef<(typeof import("./composables/useBroadcastChannel"))["useTabSync"]>;
    readonly useTargetDateCountdown: UnwrapRef<(typeof import("./composables/useCountdown"))["useTargetDateCountdown"]>;
    readonly useTaskQueue: UnwrapRef<(typeof import("./composables/useQueue"))["useTaskQueue"]>;
    readonly useTemplateRef: UnwrapRef<(typeof import("vue"))["useTemplateRef"]>;
    readonly useThrottledVModel: UnwrapRef<(typeof import("./composables/useVModel"))["useThrottledVModel"]>;
    readonly useTimeout: UnwrapRef<(typeof import("./composables/useTimer"))["useTimeout"]>;
    readonly useTimeoutFn: UnwrapRef<(typeof import("./composables/useTimer"))["useTimeoutFn"]>;
    readonly useTimestamp: UnwrapRef<(typeof import("./composables/useTimer"))["useTimestamp"]>;
    readonly useTimestampedHistory: UnwrapRef<(typeof import("./composables/useHistory"))["useTimestampedHistory"]>;
    readonly useTitle: UnwrapRef<(typeof import("./composables/useTitle"))["useTitle"]>;
    readonly useTitleTemplate: UnwrapRef<(typeof import("./composables/useTitle"))["useTitleTemplate"]>;
    readonly useToggle: UnwrapRef<(typeof import("./composables/useVModel"))["useToggle"]>;
    readonly useTransition: UnwrapRef<(typeof import("./composables/useTransition"))["useTransition"]>;
    readonly useTransitionGroup: UnwrapRef<(typeof import("./composables/useTransition"))["useTransitionGroup"]>;
    readonly useTypewriter: UnwrapRef<(typeof import("./composables/useTransition"))["useTypewriter"]>;
    readonly useUnmounted: UnwrapRef<(typeof import("./composables/useLifecycle"))["useUnmounted"]>;
    readonly useUpdated: UnwrapRef<(typeof import("./composables/useLifecycle"))["useUpdated"]>;
    readonly useVModel: UnwrapRef<(typeof import("./composables/useVModel"))["useVModel"]>;
    readonly useVModels: UnwrapRef<(typeof import("./composables/useVModel"))["useVModels"]>;
    readonly useVerificationCode: UnwrapRef<(typeof import("./composables/useCountdown"))["useVerificationCode"]>;
    readonly useVisibility: UnwrapRef<(typeof import("./composables/useIntersectionObserver"))["useVisibility"]>;
    readonly useWatchArray: UnwrapRef<(typeof import("./composables/useWatch"))["useWatchArray"]>;
    readonly useWebSocket: UnwrapRef<(typeof import("./composables/useWebSocket"))["useWebSocket"]>;
    readonly useWebSocketBinary: UnwrapRef<(typeof import("./composables/useWebSocket"))["useWebSocketBinary"]>;
    readonly useWebSocketJSON: UnwrapRef<(typeof import("./composables/useWebSocket"))["useWebSocketJSON"]>;
    readonly useWindowSize: UnwrapRef<(typeof import("./composables/useWindowSize"))["useWindowSize"]>;
    readonly vClickOutside: UnwrapRef<(typeof import("./composables/useClickOutside"))["vClickOutside"]>;
    readonly validateImage: UnwrapRef<(typeof import("./composables/useImage"))["validateImage"]>;
    readonly watch: UnwrapRef<(typeof import("vue"))["watch"]>;
    readonly watchArray: UnwrapRef<(typeof import("./composables/useWatch"))["watchArray"]>;
    readonly watchAtMost: UnwrapRef<(typeof import("./composables/useWatch"))["watchAtMost"]>;
    readonly watchDebounced: UnwrapRef<(typeof import("./composables/useWatch"))["watchDebounced"]>;
    readonly watchEffect: UnwrapRef<(typeof import("vue"))["watchEffect"]>;
    readonly watchIgnorable: UnwrapRef<(typeof import("./composables/useWatch"))["watchIgnorable"]>;
    readonly watchOnce: UnwrapRef<(typeof import("./composables/useWatch"))["watchOnce"]>;
    readonly watchPausable: UnwrapRef<(typeof import("./composables/useWatch"))["watchPausable"]>;
    readonly watchPostEffect: UnwrapRef<(typeof import("vue"))["watchPostEffect"]>;
    readonly watchReactive: UnwrapRef<(typeof import("./composables/useReactive"))["watchReactive"]>;
    readonly watchSyncEffect: UnwrapRef<(typeof import("vue"))["watchSyncEffect"]>;
    readonly watchThrottled: UnwrapRef<(typeof import("./composables/useWatch"))["watchThrottled"]>;
    readonly watchTriggered: UnwrapRef<(typeof import("./composables/useWatch"))["watchTriggered"]>;
    readonly watchWithFilter: UnwrapRef<(typeof import("./composables/useWatch"))["watchWithFilter"]>;
    readonly whenever: UnwrapRef<(typeof import("./composables/useWatch"))["whenever"]>;
    readonly writableComputed: UnwrapRef<(typeof import("./composables/useComputed"))["writableComputed"]>;
  }
}
