/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./components/AppBreadcrumb.vue')['default']
    AvatarUploader: typeof import('./components/AvatarUploader.vue')['default']
    BackToTop: typeof import('./components/BackToTop.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    CopyButton: typeof import('./components/CopyButton.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    LoadingOverlay: typeof import('./components/LoadingOverlay.vue')['default']
    PageTransition: typeof import('./components/PageTransition.vue')['default']
    PasswordStrengthIndicator: typeof import('./components/PasswordStrengthIndicator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonLoader: typeof import('./components/SkeletonLoader.vue')['default']
  }
}
